export const ICON = {
  ACCOUNTS: 'wallet',
  ADD: 'plus',
  ALERT: 'triangle-alert',
  BACK: 'chevron-left',
  BACKSPACE: 'delete',
  BIOMETRIC: 'fingerprint',
  BIOMETRIC_FACE: 'scan-face',
  CHECK: 'check',
  CLOSE: 'x',
  DOWN: 'chevron-down',
  INFO: 'info',
  RECEIPT: 'receipt-text',
  RIGHT: 'chevron-right',
  SEARCH: 'search',
  STAR: 'star',
};
