export const ICON = {
  // navigation
  BACK: 'arrow-left',
  CLOSE: 'close',
  // transaction
  INCOME: 'arrow-up-bold-outline',
  EXPENSE: 'arrow-down-bold-outline',
  SWAP: 'transfer',
  // footer
  HOME: 'home-outline',
  STATS: 'chart-line-variant',
  ACCOUNTS: 'book-multiple-outline',
  SETTINGS: 'cog-outline',
  // notifications
  ALERT: 'alert-outline',
  INFO: 'information-outline',
  SUCCESS: 'check-circle-outline',
  // food & drinks
  FOOD: 'silverware-variant',
  COFFEE: 'coffee-outline',
  TEA: 'tea-outline',
  DESSERT: 'cake-variant-outline',
  BAKERY: 'food-croissant',
  BURGER: 'hamburger',
  MEAT: 'food-steak',
  FRUIT: 'food-apple-outline',
  FISH: 'fish',
  DAIRY: 'cow',
  EGG: 'egg-outline',
  BREAD: 'bread-slice-outline',
  SNACK: 'candy-outline',
  ICECREAM: 'ice-cream',
  GROCERY: 'cart-outline',
  NUT: 'peanut-outline',
  VEGETABLE: 'seed-outline',
  // travel
  TRAVEL: 'passport',
  CAR: 'car',
  TAXI: 'taxi',
  BUS: 'bus',
  AIRPLANE: 'airplane',
  PASSPORT: 'passport',
  MOTORBIKE: 'motorbike',
  BOAT: 'sail-boat',
  TRAIN: 'train',
  SUBWAY: 'subway-variant',
  PARKING: 'parking',
  SUITCASE: 'bag-suitcase-outline',
  TICKET: 'ticket-confirmation-outline',
  HOTEL: 'office-building-outline',
  // debt
  // DEBT: 'bank-outline',
  DEBT: 'bank-transfer-in',
  SALARY: 'bank-transfer-out',
  CONTRACT: 'file-document-outline',
  // investment
  INVESTMENT: 'trending-up',
  // INVESTMENT: 'stack-overflow',
  GOLD: 'gold',
  BITCOIN: 'bitcoin',
  // entertainment
  ENTERTAINMENT: 'movie-open-outline',
  MOVIE: 'movie-open-outline',
  // shopping
  SHOPPING: 'shopping-outline',
  TSHIRT: 'tshirt-crew-outline',
  SHOE: 'shoe-sneaker',
  RUN: 'run',
  APPLE: 'apple',
  WATCH: 'watch',
  TREE: 'tree-outline',
  // utilities
  UTILITIES: 'lightbulb-on-outline',
  WIFI: 'wifi',
  PHONE: 'cellphone',
  GASOLINE: 'gas-station-outline',
  ELECTRICITY: 'lightbulb-on-outline',
  WATER: 'water-outline',
  APARTMENT: 'apartment',
  // healthcare
  HOSPITAL: 'hospital-box-outline',
  PILL: 'pill',
  DOCTOR: 'doctor',
  // PERSONAL
  PERSONAL: 'bag-personal-outline',
  // services
  SERVICES: 'room-service-outline',
  GARDEN: 'grass',
  NETFLIX: 'netflix',
  SPOTIFY: 'spotify',
  ICLOUD: 'apple-icloud',
  PAYPAL: 'alpha-p-box',
  LAUNDRY: 'local-laundry-service',
  // Transfer
  TRANSFER: 'bank-transfer',
  // Others
  OTHERS: 'swap-horizontal-variant',
  // pasives
  PASIVE: 'calendar-import',
  // -- customs
  // banks
  KASIKORN: 'alpha-k-box-outline',
  KRUNGTHAI: 'alpha-k-box',
  WISE: 'alpha-w-box-outline',
  N26: 'alpha-n-box-outline',
  ING: 'alpha-i-box-outline',
  REVOLUT: 'alpha-r-box-outline',
  // family
  BENJI: 'baby',
  CHANA: 'face-woman',
  EKI: 'google-street-view',
  YURI: 'face-woman',
  //
  UNKNOWN: 'block-helper',
  TRASH: 'trash-can-outline',
};
