export const theme = {
  colors: {
    light: {
      background: '#F6F4EE',
      surface: '#EEEBE0',
      surfaceSoft: '#E6E2D5',
      text: '#15140F',
      textSecondary: '#3D3A31',
      textMuted: '#6E6857',
      border: '#DCD7C7',
      rule: '#15140F',
      accent: '#FFBC2D',
      onAccent: '#2A2008',
      accentSoft: '#F6E7C0',
      onAccentSoft: '#2A2008',
      positive: '#87620E',
      danger: '#A8442A',
      dangerSoft: '#F0E0DA',
      warning: '#A87515',
      success: '#87620E',
      overlay: 'rgba(21, 20, 15, 0.36)',
      inverse: '#15140F',
      onInverse: '#F6F4EE',
    },
    dark: {
      background: '#14130E',
      surface: '#1E1C16',
      surfaceSoft: '#2A2720',
      text: '#F2EEE2',
      textSecondary: '#C9C3B2',
      textMuted: '#8A8474',
      border: '#2C2A22',
      rule: '#6E695C',
      accent: '#FFC94D',
      onAccent: '#2A2008',
      accentSoft: '#3A2F14',
      onAccentSoft: '#F2EEE2',
      positive: '#E9BE55',
      danger: '#D08163',
      dangerSoft: '#3A241C',
      warning: '#D0A54A',
      success: '#E9BE55',
      overlay: 'rgba(0, 0, 0, 0.55)',
      inverse: '#F2EEE2',
      onInverse: '#14130E',
    },
  },
  typography: {
    fontFamily: 'font-default',
    families: {
      primary: 'font-default',
      mono: 'font-mono',
    },
    fontFaces: {
      regular: 'font-default',
      medium: 'font-medium',
      bold: 'font-bold',
      mono: 'font-mono',
      monoMedium: 'font-mono-medium',
    },
    sizes: {
      micro: 10,
      tiny: 11,
      caption: 12,
      body: 14,
      subtitle: 15,
      heading: 22,
      title: 28,
    },
    lineHeights: {
      micro: 14,
      tiny: 15,
      caption: 16,
      body: 19,
      subtitle: 20,
      heading: 28,
      title: 32,
    },
    // Figures live on their own ramp: monospaced, tabular, tighter tracking.
    figureSizes: {
      xs: 10,
      sm: 12,
      md: 14,
      lg: 19,
      xl: 26,
      hero: 36,
    },
    figureLineHeights: {
      xs: 14,
      sm: 16,
      md: 19,
      lg: 24,
      xl: 30,
      hero: 40,
    },
    iconSizes: {
      xxs: 11,
      tiny: 13,
      caption: 15,
      body: 17,
      subtitle: 20,
      title: 24,
    },
    tracking: {
      eyebrow: 1.4,
      title: -0.56,
      figure: -0.3,
    },
  },
  spacing: {
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 32,
    xxl: 48,
  },
  // Three radii, and no more: flat blocks, 4 for anything touchable, full for dots.
  borderRadius: {
    none: 0,
    sm: 4,
    md: 4,
    lg: 4,
    xl: 4,
    full: 9999,
  },
  // Separation is hairlines, never elevation — with one exception: a dropdown floats over
  // live content with no scrim behind it, so it is the only surface allowed to lift off the page.
  shadows: {
    sm: {},
    md: {},
    lg: {},
    overlay: {
      elevation: 6,
      shadowColor: '#15140F',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.16,
      shadowRadius: 16,
    },
  },
  hairline: 1,
  animations: {
    duration: {
      standard: 350,
      quick: 250,
    },
  },
};
