import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (file) => readFileSync(join(ROOT, file), 'utf8');

// The app's own modules, evaluated as they are: no bundler, so imports are dropped and named exports collected.
const evaluate = (file, scope = {}) => {
  const names = [...read(file).matchAll(/^export const (\w+)/gm)].map((m) => m[1]);
  const code = read(file)
    .replace(/^import .*$/gm, '')
    .replace(/^export const /gm, 'const ')
    .replace(/^export \{[^}]*\};?$/gm, '');
  const exports = {};
  new Function('exports', ...Object.keys(scope), `${code}\nObject.assign(exports, { ${names.join(', ')} });`)(
    exports,
    ...Object.values(scope),
  );
  return exports;
};

const PKG = JSON.parse(read('package.json'));
const { theme } = evaluate('src/theme/theme.js');
const layout = evaluate('src/theme/layout.js', { theme });
const { EN: L } = evaluate('src/i18n/dictionaries.js');
const { ICON } = evaluate('src/modules/icon.js');
const { GLYPHS } = evaluate('src/primitives/Icon/glyphs.js');
const { C } = evaluate('src/modules/constants.js', { Platform: { OS: 'ios', Version: 0 }, PKG, __DEV__: false });

const BASE = 'USD';
const VERSION = PKG.version;
const FONT_SANS = "'Euclid Circular A', 'Helvetica Neue', Arial, sans-serif";
const FONT_MONO = "'Geist Mono', ui-monospace, Menlo, monospace";

const kebab = (key) => key.replace(/([A-Z])/g, '-$1').toLowerCase();
const esc = (value) => String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export const tokensCss = () => {
  const colours = (mode) =>
    Object.entries(theme.colors[mode])
      .map(([key, value]) => `  --color-${kebab(key)}: ${value};`)
      .join('\n');
  const spacing = Object.entries(theme.spacing)
    .map(([key, value]) => `  --space-${key}: ${value}px;`)
    .join('\n');
  const geometry = Object.entries(layout)
    .map(([key, value]) => `  --${kebab(key)}: ${value}px;`)
    .join('\n');
  return `/* Generated by yarn design from src/theme/theme.js and src/theme/layout.js. Do not edit. */
:root {
${colours('light')}
  --font-sans: ${FONT_SANS};
  --font-mono: ${FONT_MONO};
${spacing}
  --radius-sm: ${theme.borderRadius.sm}px;
  --radius-full: ${theme.borderRadius.full}px;
  --hairline: ${theme.hairline}px;
  --motion-quick: ${theme.animations.duration.quick}ms;
  --motion-standard: ${theme.animations.duration.standard}ms;
${geometry}
}
:root.dark {
${colours('dark')}
}
`;
};

const TONE = { muted: 'muted', secondary: 'secondary', accent: 'accent', positive: 'positive', danger: 'danger', onAccent: 'on-accent', onAccentSoft: 'on-accent-soft', onInverse: 'on-inverse' };
const ICON_SIZES = { xxs: 11, xs: 13, s: 15, m: 17, l: 20, xl: 24 };

const icon = (name, { size = 'm', tone } = {}) => {
  const glyph = GLYPHS[name];
  if (!glyph) return '';
  const px = typeof size === 'number' ? size : ICON_SIZES[size];
  const colour = tone ? `color: var(--color-${kebab(tone)})` : '';
  return `<svg width="${px}" height="${px}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" style="flex-shrink:0;${colour}">${glyph.map((d) => `<path d="${d}"/>`).join('')}</svg>`;
};

const text = (content, { size = 'm', tone, medium, bold, center, uppercase, style = '' } = {}) => {
  const classes = ['m-text', size !== 'm' ? size : '', TONE[tone] || '', medium ? 'medium' : '', bold ? 'bold' : '', center ? 'center' : '', uppercase ? 'uppercase' : ''].filter(Boolean).join(' ');
  return `<span class="${classes}"${style ? ` style="${style}"` : ''}>${esc(content)}</span>`;
};

const fig = (content, { size = 'md', tone, bold, style = '' } = {}) =>
  `<span class="m-fig ${size}${bold ? ' bold' : ''}${TONE[tone] ? ` ${TONE[tone]}` : ''}"${style ? ` style="${style}"` : ''}>${content}</span>`;

const decimals = (value, currency) => {
  const max = C.FIXED[currency] !== undefined ? C.FIXED[currency] : 2;
  if (max <= 2) return max;
  const [, rest = ''] = Math.abs(value).toFixed(max).split('.');
  return Math.max(2, rest.replace(/0+$/, '').length);
};
const formatters = new Map();
const format = (value, places) => {
  if (!formatters.has(places)) formatters.set(places, new Intl.NumberFormat('en-US', { minimumFractionDigits: places, maximumFractionDigits: places }));
  return formatters.get(places).format(Math.abs(value));
};

// PriceFriendly: sign, whole, muted cents, and the symbol only for a foreign currency.
const price = (value, { currency = BASE, size = 'md', bold, tone, operator, symbol, masked, fixed } = {}) => {
  const resolvedTone = tone !== undefined ? tone : operator && value > 0 ? 'positive' : undefined;
  if (masked) return fig('••••', { size, bold, tone: resolvedTone });
  const formatted = format(value, fixed !== undefined ? fixed : decimals(value, currency));
  const dot = formatted.lastIndexOf('.');
  const whole = dot < 0 ? formatted : formatted.slice(0, dot);
  const cents = dot < 0 ? '' : formatted.slice(dot);
  const sign = value < 0 ? '−' : operator && value > 0 ? '+' : '';
  const mark = symbol && currency !== BASE ? `<span class="symbol">${esc(C.SYMBOL[currency] || currency)}</span>` : '';
  return `<span class="m-price">${fig(`${sign}${whole}${cents ? `<span class="cents">${cents}</span>` : ''}${mark ? ` ${mark}` : ''}`, { size, bold, tone: resolvedTone })}</span>`;
};

const percent = (value, { places = 1, signed = true } = {}) => `${signed && value > 0 ? '+' : value < 0 ? '−' : ''}${Math.abs(value).toFixed(places)}%`;

const delta = (value, { caption, plain, inverted, places = 1, size = 'xs' } = {}) => {
  const wanted = inverted ? value < 0 : value > 0;
  const figure = fig(percent(value, { places }), { size, tone: wanted ? 'positive' : undefined });
  return `<span class="m-delta">${plain ? figure : `<span class="chip${wanted ? ' wanted' : ''}">${figure}</span>`}${caption ? text(caption, { size: 'xxs', tone: 'muted' }) : ''}</span>`;
};

const eyebrow = (content, { tone, style = '' } = {}) => `<span class="m-eyebrow${tone ? ` ${tone}` : ''}"${style ? ` style="${style}"` : ''}>${esc(content)}</span>`;
const heading = (value, { eyebrow: label, actions = '' } = {}) => `<div class="m-heading"><b>${esc(value)}</b>${label ? eyebrow(label) : ''}${actions ? `<span class="actions">${actions}</span>` : ''}</div>`;
const btn = (label, { variant = 'primary', size = 'm', disabled, grow, iconName } = {}) =>
  `<span class="m-btn${variant !== 'primary' ? ` ${kebab(variant)}` : ''}${size !== 'm' ? ` ${size}` : ''}${disabled ? ' disabled' : ''}${grow ? ' grow' : ''}${iconName && !label ? ' icon' : ''}">${iconName ? icon(iconName, { size: 'l' }) : ''}${label ? esc(label) : ''}</span>`;
const chip = (label, { variant = 'muted', size = 'xs', iconName, iconRight, shape } = {}) =>
  `<span class="m-chip${variant !== 'muted' ? ` ${variant}` : ''}${size === 's' ? ' s' : ''}${shape === 'circle' ? ' circle' : ''}">${iconName ? icon(iconName, { size: 'xxs' }) : ''}${esc(label)}${iconRight ? icon(iconRight, { size: 'xxs' }) : ''}</span>`;
const check = (on) => `<span class="m-check${on ? ' on' : ''}">${on ? icon(ICON.CHECK, { size: 'xxs' }) : ''}</span>`;
const switchEl = (on) => `<span class="m-switch${on ? ' on' : ''}"></span>`;
const seg = (options, value, { compact, auto } = {}) =>
  `<div class="m-seg${compact ? ' compact' : ''}${auto ? ' auto' : ''}">${options.map((option) => `<span${option === value ? ' class="on"' : ''}>${esc(option)}</span>`).join('')}</div>`;
const iconButton = (name) => `<span class="m-iconbtn">${icon(name)}</span>`;
const seal = (floating) => `<span class="m-seal${floating ? ' floating' : ''}">${icon(ICON.ADD, { size: 'l' })}</span>`;
const logo = () => `<span class="m-logo">MÔNEY</span>`;
const mark = (size = 44) => `<span class="m-mark" style="width:${size}px;height:${size}px;font-size:${Math.round(size * 0.42)}px">MÔ</span>`;

const fieldRow = (label, value, { divider, chevron } = {}) =>
  `<div class="m-fieldrow${divider ? ' divider' : ''}"><span class="label">${esc(label)}</span><span class="value">${value}</span>${chevron ? icon(ICON.DOWN, { size: 's', tone: 'textMuted' }) : ''}</div>`;
const input = (value, { placeholder = '...', right, figure } = {}) =>
  `<span class="m-input${right ? ' right' : ''}${figure ? ' figure' : ''}">${value ? esc(value) : `<span class="placeholder">${esc(placeholder)}</span>`}</span>`;
const setting = (title, { subtitle, right = '', divider, tone } = {}) =>
  `<div class="m-setting${divider ? ' divider' : ''}"><span class="text">${text(title, { medium: true, tone })}${subtitle ? `<br>${text(subtitle, { size: 'xs', tone: 'muted' })}` : ''}</span><span class="right">${right}</span></div>`;
const chevronRight = () => icon(ICON.RIGHT, { size: 's', tone: 'textMuted' });
const rightValue = (value, { figure } = {}) => `${figure ? fig(esc(value), { size: 'sm', tone: 'muted' }) : text(value, { size: 's', tone: 'muted' })}${chevronRight()}`;

const masthead = ({ section, back, sheet, actions = '', search, rule = true } = {}) => {
  const left = search
    ? `<span class="left" style="flex:1;height:34px;border:var(--hairline) solid var(--color-border);border-radius:var(--radius-sm);padding:0 12px;gap:8px">${icon(ICON.SEARCH, { size: 's', tone: 'textMuted' })}${input('', { placeholder: `${L.SEARCH}…` })}</span>`
    : back
      ? `<span class="left">${iconButton(ICON.BACK)}<span class="m-title">${esc(section)}</span></span>`
      : `<span class="left">${logo()}</span>`;
  const right = search
    ? iconButton(ICON.CLOSE)
    : `<span class="right">${!back && section ? eyebrow(section) : ''}${actions}${sheet ? iconButton(ICON.CLOSE) : ''}</span>`;
  return `<div class="m-masthead">${left}${right}</div>${rule && !sheet ? '<div class="m-rule"></div>' : ''}`;
};

const TABS = [L.OVERVIEW, L.ACCOUNTS, null, L.ACTIVITY, L.SETTINGS];
const footer = (active) =>
  `<div class="m-footer">${TABS.map((tab) => (tab === null ? seal() : `<span class="tab${tab === active ? ' on' : ''}">${text(tab, { size: 'xs', medium: tab === active, tone: tab === active ? undefined : 'muted' })}</span>`)).join('')}</div>`;
const statusBar = () => `<div class="m-status"><span class="figure">9:41</span><span class="figure">●●●</span></div>`;

const phone = (name, caption, body, { sheet, fold, tab } = {}) =>
  `<div class="kit-board" data-screen="${name}"><div class="kit-caption">${esc(caption)}</div><div class="m kit-phone${sheet ? ' sheet' : ''}${fold ? ' fold' : ''}">${statusBar()}${body}${tab ? footer(tab) : ''}</div></div>`;
const content = (body, style = '') => `<div class="m-content"${style ? ` style="${style}"` : ''}>${body}</div>`;

const linePoints = (series, { width, height, padding, min, max }) =>
  series.map((value, index) => [
    padding + (index * (width - padding * 2)) / (series.length - 1),
    padding + ((max - value) * (height - padding * 2)) / (max - min || 1),
  ]);
const pathOf = (points) => points.map(([x, y], index) => `${index ? 'L' : 'M'}${x.toFixed(1)} ${y.toFixed(1)}`).join(' ');
const compact = (value) => (Math.abs(value) >= 1000 ? `${(value / 1000).toFixed(value >= 10000 ? 0 : 1)}k` : `${Math.round(value)}`);

const chart = ({ values, trend, labels, pointer }) => {
  const width = 350;
  const height = 112;
  const padding = 10;
  const all = [...values, ...trend];
  const min = Math.min(...all);
  const max = Math.max(...all);
  const points = linePoints(values, { width, height, padding, min, max });
  const trendPoints = linePoints(trend, { width, height, padding, min, max });
  const last = points[points.length - 1];
  const selected = pointer !== undefined ? points[pointer] : undefined;
  const grid = [max, (max + min) / 2, min];
  return `<div class="m-chart"><div style="position:absolute;left:0;top:${padding - 12}px;height:${height - padding * 2}px;display:flex;flex-direction:column;justify-content:space-between">${grid.map((value) => fig(compact(value), { size: 'xs', tone: 'muted' })).join('')}</div><svg viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">${grid.map((_, index) => `<line x1="0" x2="${width}" y1="${padding + (index * (height - padding * 2)) / 2}" y2="${padding + (index * (height - padding * 2)) / 2}" stroke="var(--color-border)" stroke-width="1"/>`).join('')}<path d="${pathOf(trendPoints)}" fill="none" stroke="var(--color-text-muted)" stroke-width="1.5" stroke-dasharray="3 4"/><path d="${pathOf(points)}" fill="none" stroke="var(--color-text)" stroke-width="1.5"/>${selected ? `<line x1="${selected[0]}" x2="${selected[0]}" y1="${padding}" y2="${height - padding}" stroke="var(--color-text-muted)" stroke-width="1" stroke-dasharray="2 3"/><circle cx="${selected[0]}" cy="${selected[1]}" r="4" fill="var(--color-background)" stroke="var(--color-text)" stroke-width="1.5"/>` : ''}<circle cx="${last[0]}" cy="${last[1]}" r="4" fill="var(--color-accent)"/></svg><div class="m-axis">${labels.map((label) => eyebrow(label)).join('')}</div><div class="m-chart-legend"><span><i style="display:inline-block;width:14px;height:0;border-top:1.5px solid var(--color-text)"></i>${text(L.BALANCE, { size: 'xxs', tone: 'muted' })}</span><span><i style="display:inline-block;width:14px;height:0;border-top:1.5px dashed var(--color-text-muted)"></i>${text(L.TREND, { size: 'xxs', tone: 'muted' })}</span></div></div>`;
};

const flowChart = ({ incomes, expenses, labels, selected }) => {
  const width = 350;
  const height = 132;
  const slot = width / 6;
  const baseline = height / 2;
  const peak = Math.max(...incomes, ...expenses);
  const scale = (baseline - 12) / peak;
  const median = (list) => [...list].sort((a, b) => a - b)[Math.floor(list.length / 2)];
  const bars = incomes.map((income, index) => {
    const x = index * slot + slot * 0.25;
    const w = slot * 0.5;
    const up = income * scale;
    const down = expenses[index] * scale;
    return `<rect x="${x.toFixed(1)}" y="${(baseline - up).toFixed(1)}" width="${w.toFixed(1)}" height="${up.toFixed(1)}" fill="var(--color-accent)"/><rect x="${x.toFixed(1)}" y="${baseline}" width="${w.toFixed(1)}" height="${down.toFixed(1)}" fill="var(--color-text)"/>`;
  });
  const incomeY = baseline - median(incomes) * scale;
  const expenseY = baseline + median(expenses) * scale;
  return `<div class="m-chart"><svg viewBox="0 0 ${width} ${height}" width="${width}" height="${height}"><line x1="0" x2="${width}" y1="${baseline}" y2="${baseline}" stroke="var(--color-border)"/><line x1="0" x2="${width}" y1="${incomeY.toFixed(1)}" y2="${incomeY.toFixed(1)}" stroke="var(--color-accent)" stroke-dasharray="2 3"/><line x1="0" x2="${width}" y1="${expenseY.toFixed(1)}" y2="${expenseY.toFixed(1)}" stroke="var(--color-text-muted)" stroke-dasharray="2 3"/>${bars.join('')}${selected !== undefined ? `<rect x="${(selected * slot).toFixed(1)}" y="0" width="${slot.toFixed(1)}" height="${height}" fill="var(--color-text)" opacity="0.06"/>` : ''}</svg><div class="m-axis" style="display:grid;grid-template-columns:repeat(6,1fr);text-align:center">${labels.map((label, index) => eyebrow(label, { tone: index === selected ? 'ink' : undefined })).join('')}</div><div class="m-chart-legend"><span><i class="m-dot" style="background:var(--color-accent)"></i>${text(L.FLOW_IN, { size: 'xxs', tone: 'muted' })}</span><span><i class="m-dot" style="background:var(--color-text)"></i>${text(L.FLOW_OUT, { size: 'xxs', tone: 'muted' })}</span><span><i style="display:inline-block;width:14px;border-top:1px dashed var(--color-text-muted)"></i>${text(L.TYPICAL, { size: 'xxs', tone: 'muted' })}</span></div></div>`;
};

const txRow = ({ time, title, category, value, currency, base, income }) =>
  `<div class="m-row"><span class="time">${fig(time, { size: 'xs', tone: 'muted' })}</span><span class="text">${text(title, { medium: true })}${text(category, { size: 'xxs', tone: 'muted' })}</span><span class="amount">${price(income ? value : -value, { currency, size: 'md', bold: true, operator: income, symbol: true })}${base !== undefined ? price(income ? base : -base, { size: 'xs', tone: 'muted' }) : ''}</span></div>`;
const dayHead = (label, net) => `<div class="m-dayhead">${eyebrow(label, { tone: 'ink' })}${net ? price(net, { size: 'xs', operator: true, tone: net > 0 ? 'positive' : 'muted' }) : ''}</div>`;
const accountRow = ({ title, currency, balance, base, change }) =>
  `<div class="m-row" style="padding:10px 0"><span class="text">${text(title, { medium: true })}${text(currency, { size: 'xxs', tone: 'muted' })}</span><span class="amount">${price(balance, { currency, size: 'lg', bold: true, symbol: true })}${base !== undefined ? price(base, { size: 'xs', tone: 'muted' }) : change !== undefined ? delta(change, { plain: true }) : fig('—', { size: 'xs', tone: 'muted' })}</span></div>`;

const monthSummary = ({ spent, baseline, pace, day, swing, swingCategory, scheduled, pending, closed, closedHint }) => {
  const scale = Math.max(spent, baseline);
  const fill = Math.min(spent, baseline) / scale;
  const line = (label, value, hint, { action, operator, tone } = {}) => `<div style="display:flex;align-items:baseline;gap:8px;padding:7px 0;border-bottom:var(--hairline) solid var(--color-border)"><span style="width:96px">${text(label, { size: 's', tone: 'muted' })}</span><span style="flex:1">${price(value, { size: 'md', operator, tone })}</span>${action ? `<span style="display:flex;align-items:center;gap:4px">${eyebrow(action, { tone: 'ink' })}${icon(ICON.RIGHT, { size: 's', tone: 'textMuted' })}</span>` : text(hint, { size: 'xs', tone: 'muted' })}</div>`;
  return `<div style="margin-top:4px"><div style="padding:8px 0 12px;border-bottom:var(--hairline) solid var(--color-border)"><div style="display:flex;align-items:baseline;gap:8px"><span style="width:96px">${text(L.SPENT_SO_FAR, { size: 's', tone: 'muted' })}</span><span style="flex:1">${price(spent, { size: 'md' })}</span>${text(pace, { size: 'xs', tone: 'muted' })}</div><div class="m-bar" style="margin:9px 0 6px"><div class="fill" style="width:${(fill * 100).toFixed(1)}%"></div><span class="tick" style="left:${((baseline / scale) * 100).toFixed(1)}%"></span></div><div style="display:flex;align-items:baseline;gap:4px">${text(`${L.USUAL_BY(day)} · `, { size: 'xxs', tone: 'muted' })}${price(baseline, { size: 'xs', tone: 'muted' })}</div></div>${closed !== undefined ? line(L.LAST_MONTH, closed, closedHint) : ''}${line(L.SWING, swing, swingCategory)}${line(L.SCHEDULED_AHEAD, scheduled, undefined, { action: L.SEE_ALL_COUNT(pending), operator: true })}</div>`;
};

const NAV = [
  ['index.html', 'System'],
  ['mobile.html', 'Mobile'],
  ['proposals.html', 'Open work'],
];
const FACTS = `<div class="kit-facts"><span>sources src/theme/theme.js · src/theme/layout.js · src/i18n · src/modules/icon.js · ROADMAP.md</span><span>type Euclid Circular A · Geist Mono</span><span>icons Lucide · 1.5 stroke</span><span>regenerate yarn design</span></div>`;

const page = ({ file, title, intro, body }) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Môney design · ${esc(title)}</title>
<link rel="stylesheet" href="tokens.css">
<link rel="stylesheet" href="kit.css">
<script src="kit.js" defer></script>
</head>
<body class="kit">
<header class="kit-header"><a class="kit-brand" href="index.html">MÔNEY</a><nav class="kit-nav" aria-label="Design kit">${NAV.map(([href, label]) => `<a href="${href}"${href === file ? ' aria-current="page"' : ''}>${label}</a>`).join('')}</nav><span class="kit-version">v${VERSION} · iOS and Android</span><div class="kit-theme" role="group" aria-label="Theme"><button type="button" data-kit-theme="light">Light</button><button type="button" data-kit-theme="dark">Dark</button></div></header>
<main class="kit-main">
<section class="kit-intro"><h1>${esc(title)}</h1><p>${intro}</p>${FACTS}</section>
${body}
</main>
</body>
</html>
`;

let counter = 0;
const section = (title, body, note) => `<section class="kit-section"><h2>${esc(title)}<span>${String(++counter).padStart(2, '0')}</span></h2>${note ? `<p>${note}</p>` : ''}${body}</section>`;
const cell = (caption, body, { component, wide, sheet, stack, row } = {}) =>
  `<div class="kit-cell"${component ? ` data-component="${component}"` : ''}${wide ? ' style="grid-column: span 2"' : ''}><div class="kit-caption">${esc(caption)}</div><div class="m kit-specimen${sheet ? ' sheet' : ''}${stack ? ' stack' : ''}${row ? ' row' : ''}">${body}</div></div>`;
const grid = (cells, wide) => `<div class="kit-grid${wide ? ' wide' : ''}">${cells.join('')}</div>`;

const COLOUR_GROUPS = [
  ['Paper and ink', ['background', 'surface', 'surfaceSoft', 'text', 'textSecondary', 'textMuted', 'border', 'rule']],
  ['Accent', ['accent', 'onAccent', 'accentSoft', 'onAccentSoft']],
  ['Semantic', ['positive', 'danger', 'dangerSoft', 'warning', 'success']],
  ['Inverse and overlay', ['inverse', 'onInverse', 'overlay']],
];

const system = () => {
  counter = 0;
  const colours = COLOUR_GROUPS.map(([title, keys]) => `<div class="kit-cell"><div class="kit-caption">${title}</div><div class="kit-swatches">${keys.map((key) => `<div class="kit-swatch" data-token="color-${kebab(key)}"><i style="background: var(--color-${kebab(key)})"></i><b>${key}</b><code>${theme.colors.light[key]}</code></div>`).join('')}</div></div>`).join('');

  const copyRamp = Object.entries(theme.typography.sizes).map(([name, size]) => `<div style="display:flex;align-items:baseline;gap:12px"><span style="width:110px">${fig(`${name} · ${size}/${theme.typography.lineHeights[name]}`, { size: 'xs', tone: 'muted' })}</span><span class="m-text" style="font-size:${size}px;line-height:${theme.typography.lineHeights[name]}px${name === 'title' ? ';letter-spacing:-0.56px' : ''}">A month that explains itself</span></div>`).join('');
  const figureRamp = Object.entries(theme.typography.figureSizes).map(([name, size]) => `<div style="display:flex;align-items:baseline;gap:12px"><span style="width:110px">${fig(`${name} · ${size}/${theme.typography.figureLineHeights[name]}`, { size: 'xs', tone: 'muted' })}</span>${price(12480.55, { size: name })}</div>`).join('');
  const weights = `<div style="display:flex;gap:16px;flex-wrap:wrap">${text('Regular 400', {})}${text('Medium 500', { medium: true })}${text('Semibold 600', { bold: true })}${fig('Mono 400', {})}${fig('Mono 500', { bold: true })}${eyebrow('Eyebrow · tracked 1.4')}</div>`;

  const icons = Object.entries(ICON).map(([key, name]) => `<span style="display:inline-flex;flex-direction:column;align-items:center;gap:6px;width:72px">${icon(name, { size: 'xl' })}${fig(key.toLowerCase(), { size: 'xs', tone: 'muted' })}</span>`).join('');
  const iconSizes = Object.entries(ICON_SIZES).map(([name, px]) => `<span style="display:inline-flex;align-items:center;gap:6px">${icon(ICON.STAR, { size: name })}${fig(`${name} ${px}`, { size: 'xs', tone: 'muted' })}</span>`).join('');

  const spacing = Object.entries(theme.spacing).map(([name, value]) => `<div style="display:flex;align-items:center;gap:12px"><span style="width:64px">${fig(`${name} · ${value}`, { size: 'xs', tone: 'muted' })}</span><i style="display:block;height:12px;width:${value * 3}px;background:var(--color-accent)"></i></div>`).join('');
  const radii = `<div style="display:flex;gap:16px;align-items:flex-end">${[['none', 0, 'flat blocks'], ['sm', 4, 'anything touchable'], ['full', 9999, 'dots']].map(([name, value, use]) => `<div style="display:flex;flex-direction:column;align-items:center;gap:6px"><i style="display:block;width:44px;height:44px;border:var(--hairline) solid var(--color-text);border-radius:${value}px"></i>${fig(`${name} · ${value}`, { size: 'xs', tone: 'muted' })}${text(use, { size: 'xxs', tone: 'muted' })}</div>`).join('')}</div>`;
  const rules = `<div class="stack" style="display:flex;flex-direction:column;gap:10px"><div style="height:var(--hairline);background:var(--color-border)"></div>${text('border · separates rows and fields', { size: 'xs', tone: 'muted' })}<div style="height:var(--hairline);background:var(--color-rule)"></div>${text('rule · closes a heading and the masthead', { size: 'xs', tone: 'muted' })}<div class="m-dropdown" style="width:auto;padding:12px">${text('overlay · the one lifted surface: a dropdown over live content', { size: 'xs', tone: 'muted' })}</div></div>`;
  const motion = `<table class="kit-table"><tr><th>name</th><th>duration</th><th>where</th></tr><tr><td><code>quick</code></td><td><code>${theme.animations.duration.quick} ms</code></td><td>notifications in and out, the dropdown's fade and scale from 0.95</td></tr><tr><td><code>standard</code></td><td><code>${theme.animations.duration.standard} ms</code></td><td>the push transition the floating add button waits out before springing in</td></tr><tr><td><code>shake</code></td><td>—</td><td>the lock screen on a wrong PIN</td></tr></table>`;
  const geometry = `<table class="kit-table"><tr><th>constant</th><th>px</th><th>from</th></tr>${Object.entries(layout).map(([name, value]) => `<tr><td><code>${name}</code></td><td><code>${value}</code></td><td>${text('theme.spacing', { size: 'xs', tone: 'muted' })}</td></tr>`).join('')}</table>`;

  const primitives = [
    cell('Text · sizes and tones', `${text('Body 14 · the copy size', {})}${text('Subtitle 15, bold', { size: 'l', bold: true })}${text('Caption 12, muted', { size: 's', tone: 'muted' })}${text('Tiny 11, secondary', { size: 'xs', tone: 'secondary' })}${text('Accent', { tone: 'accent' })} ${text('Positive', { tone: 'positive' })} ${text('Danger', { tone: 'danger' })}`, { component: 'Text', stack: true }),
    cell('Button · variants', `<div class="row" style="display:flex;flex-wrap:wrap;gap:8px">${btn(L.SAVE)}${btn(L.CANCEL, { variant: 'outlined' })}${btn('Secondary', { variant: 'secondary' })}${btn('Ghost', { variant: 'ghost' })}${btn(L.DELETE, { variant: 'danger' })}${btn(L.DELETE, { variant: 'dangerSoft' })}${btn(L.SAVE, { disabled: true })}</div><div style="display:flex;gap:8px;align-items:center;margin-top:12px">${btn(L.EDIT, { size: 's', variant: 'outlined' })}${btn('', { variant: 'outlined', iconName: ICON.ADD })}${btn(L.CONTINUE, { size: 'l' })}</div>`, { component: 'Button', stack: true }),
    cell('Input · blurred placeholder, typed, figure', `<div style="border:var(--hairline) solid var(--color-border);border-radius:var(--radius-sm)">${input('')}</div><div style="border:var(--hairline) solid var(--color-border);border-radius:var(--radius-sm)">${input('Coffee')}</div><div style="border:var(--hairline) solid var(--color-border);border-radius:var(--radius-sm)">${input('12.50', { right: true, figure: true })}</div>`, { component: 'Input', stack: true }),
    cell('Icon · the ramp, 1.5 stroke', `<div style="display:flex;gap:12px;flex-wrap:wrap;align-items:center">${iconSizes}</div>`, { component: 'Icon' }),
    cell('Pressable · opacity 0.92 while pressed', `<div style="display:flex;gap:12px;align-items:center">${btn('Idle', { variant: 'outlined' })}<span style="opacity:0.92">${btn('Pressed', { variant: 'outlined' })}</span></div>`, { component: 'Pressable' }),
    cell('View · row, gap, offset', `<div style="display:flex;gap:12px"><i style="flex:1;height:24px;background:var(--color-surface)"></i><i style="flex:1;height:24px;background:var(--color-surface)"></i><i style="flex:1;height:24px;background:var(--color-surface)"></i></div>${text('gap sm 12 · offset lg 20', { size: 'xs', tone: 'muted' })}`, { component: 'View', stack: true }),
    cell('ScrollView · snaps to an interval, no indicators', `<div style="display:flex;gap:12px;overflow:hidden">${[1, 2, 3].map(() => `<i style="flex:none;width:216px;height:60px;background:var(--color-surface);border-radius:var(--radius-sm)"></i>`).join('')}</div>${text('cardAccountSnap 228', { size: 'xs', tone: 'muted' })}`, { component: 'ScrollView', stack: true }),
  ];

  const components = [
    cell('Masthead · tab, panel, sheet, search', `${masthead({ section: L.OVERVIEW, actions: iconButton(ICON.SEARCH) })}<div style="height:12px"></div>${masthead({ section: L.SCHEDULED, back: true, actions: btn('', { variant: 'outlined', iconName: ICON.ADD }) })}<div style="height:12px"></div><div style="background:var(--color-surface)">${masthead({ section: L.TRANSACTION, sheet: true })}</div><div style="height:12px"></div>${masthead({ search: true })}`, { component: 'Masthead', wide: true }),
    cell('Footer · four tabs and the seal', footer(L.OVERVIEW), { component: 'Footer', wide: true }),
    cell('Eyebrow', `${eyebrow(`${L.NET_WORTH} · 4 ${L.ACCOUNTS_CAPTION(4)} · USD`)}${eyebrow(L.DATA, { tone: 'ink' })}`, { component: 'Eyebrow', stack: true }),
    cell('Heading · title, eyebrow, actions, rule', `${heading(L.THIS_MONTH, { eyebrow: 'September' })}${heading(L.ACCOUNTS, { actions: eyebrow(L.SEE_ALL_COUNT(4)) })}`, { component: 'Heading', stack: true }),
    cell('PriceFriendly · sizes, sign, symbol, mask', `${price(12480.55, { size: 'hero', bold: true })}${price(-1000, { currency: 'THB', symbol: true, bold: true })} ${price(3000, { operator: true })} ${price(0.52, { currency: 'BTC', symbol: true })} ${price(12480.55, { masked: true })}`, { component: 'PriceFriendly', stack: true }),
    cell('Delta · chip beside a hero, plain in a row', `<div style="display:flex;gap:16px;flex-wrap:wrap">${delta(3.2, { caption: L.THIS_MONTH_CAPTION })}${delta(-4.7, { caption: L.THIS_MONTH_CAPTION })}${delta(-12, { plain: true, inverted: true, places: 0 })}${delta(2.1, { plain: true })}</div>`, { component: 'Delta' }),
    cell('Chip · variants', `<div style="display:flex;gap:8px;flex-wrap:wrap">${chip('muted')}${chip('accent', { variant: 'accent' })}${chip(`${L.SUGGESTED}: Home`, { variant: 'soft', iconRight: ICON.CLOSE })}${chip('outline', { variant: 'outline' })}${chip(L.BACKUP_CTA, { variant: 'inverse', size: 's' })}${chip('3', { shape: 'circle' })}</div>`, { component: 'Chip' }),
    cell('Checkbox', `<div style="display:flex;gap:12px">${check(false)}${check(true)}</div>`, { component: 'Checkbox' }),
    cell('SegmentedToggle · flex, scrollable, compact', `${seg([L.EXPENSE, L.INCOME, L.SWAP], L.EXPENSE)}${seg([L.ALL, 'BTC', 'THB', 'EUR', 'USD'], 'BTC', { auto: true })}${seg(['6M', '1Y', L.RANGE_ALL], '1Y', { compact: true })}`, { component: 'SegmentedToggle', stack: true }),
    cell('FieldRow · label column, value, chevron', `${fieldRow(L.CONCEPT, input('Coffee', { right: true }))}${fieldRow(L.AMOUNT, `${input('65', { right: true, figure: true })}${fig('฿', { size: 'sm', tone: 'muted' })}`, { divider: true })}${fieldRow(L.CATEGORY, text('Personal', { size: 's', medium: true }), { divider: true, chevron: true })}`, { component: 'FieldRow', sheet: true }),
    cell('Setting · navigation, value, toggle, activity, action', `${setting(L.SYNC_RATES_CTA, { right: rightValue('2 h ago', { figure: true }) })}${setting(L.SCHEDULED, { divider: true, right: rightValue('4') })}${setting(L.REMINDER_BACKUP, { divider: true, subtitle: `${L.SCHEDULED_PATTERN_WEEKLY} - Sun 08:00`, right: switchEl(true) })}${setting(L.RESET_DATA, { divider: true, tone: 'danger' })}`, { component: 'Setting', wide: true }),
    cell('SettingSelect · a row that opens a dropdown', `${setting(L.THEME, { right: `${text(L.APPEARANCE_LIGHT, { size: 's', tone: 'muted' })}${icon(ICON.DOWN, { size: 's', tone: 'textMuted' })}` })}${setting(L.TEXT_SIZE, { divider: true, right: `${text(L.TEXT_SIZE_DEFAULT, { size: 's', tone: 'muted' })}${icon(ICON.DOWN, { size: 's', tone: 'textMuted' })}` })}`, { component: 'SettingSelect' }),
    cell('Dropdown · floats over live content', `<div class="m-dropdown">${[['◐', L.APPEARANCE_SYSTEM, false], ['○', L.APPEARANCE_LIGHT, true], ['●', L.APPEARANCE_DARK, false]].map(([symbol, label, on]) => `<div class="m-option"><span class="m-well s" style="background:var(--color-surface)">${fig(symbol, { size: 'lg' })}</span>${text(label, { size: 's', medium: on, style: 'flex:1' })}${on ? icon(ICON.CHECK, { size: 's', tone: 'accent' }) : ''}</div>`).join('')}</div>`, { component: 'Dropdown' }),
    cell('Field · a labelled frame; first and last round', `<div class="m-field first"><span class="label">${esc(L.NAME)}</span><span class="value">${text('Chase', { medium: true })}</span></div><div class="m-field last"><span class="label">${esc(L.CURRENCY)}</span><span class="value">${text('USD · US Dollar', { medium: true })}</span></div>`, { component: 'Field' }),
    cell('InputField', `<div class="m-field first last"><span class="label">${esc(L.NAME)}</span><span class="value">${input('Chase')}</span></div>`, { component: 'InputField' }),
    cell('InputAmount · the base equivalent as suffix', `<div class="m-field first last"><span class="label">${esc(L.INITIAL_BALANCE)}</span><span class="value" style="justify-content:space-between">${input('34596', { figure: true })}${price(1052.61, { size: 'sm', tone: 'secondary' })}</span></div>`, { component: 'InputAmount' }),
    cell('InputCurrency · symbol well', `<div class="m-field first last"><span class="label">${esc(L.CURRENCY)}</span><span class="value" style="justify-content:space-between"><span style="display:flex;align-items:center;gap:12px"><span class="m-well s">${fig('฿', { size: 'sm' })}</span>${text('THB · Thai Baht', { medium: true })}</span>${icon(ICON.DOWN, { size: 's', tone: 'textMuted' })}</span></div>`, { component: 'InputCurrency' }),
    cell('Card · a well (size s) and the active tint', `<div style="display:flex;gap:12px;align-items:center"><span class="m-well s" style="background:var(--color-surface)">${fig('$', { size: 'sm' })}</span><span style="display:inline-block;padding:12px;background:var(--color-accent-soft)">${text('active', { size: 's', tone: 'onAccentSoft' })}</span></div>`, { component: 'Card' }),
    cell('Chart · balance, trend, pointer, axis, legend', `${eyebrow(`${L.NET_WORTH} · 4 ${L.ACCOUNTS_CAPTION(4)} · USD`)}<div style="display:flex;align-items:baseline;gap:8px;margin-top:4px">${price(61648.74, { size: 'hero', bold: true })}${delta(7.2, { caption: L.STATS_RANGE_1Y_CAPTION })}</div>${chart({ values: [48, 51, 47, 52, 56, 55, 58, 54, 57, 60, 59, 61.6], trend: [47, 48.5, 49, 50, 51.5, 53, 54.5, 55, 56, 57.5, 58.5, 59.5], labels: ['Oct', 'Dec', 'Feb', 'Apr', 'Jun', 'Sep'], pointer: 8 })}`, { component: 'Chart', wide: true }),
    cell('FlowChart · incomes above, expenses below, medians, a selected month', `${heading(L.CASHFLOW)}${flowChart({ incomes: [3000, 3000, 3200, 3000, 4100, 3000], expenses: [2100, 2450, 1980, 2600, 2300, 552], labels: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], selected: 5 })}`, { component: 'FlowChart', wide: true }),
    cell('MonthSummary · the month block', `${heading(L.THIS_MONTH, { eyebrow: 'September' })}${monthSummary({ spent: 552.78, baseline: 1042.29, pace: `−47% ${L.BELOW_PACE}`, day: 9, swing: -208.11, swingCategory: 'Personal', scheduled: 1325.29, pending: 4, closed: 2980.12, closedHint: L.AS_USUAL })}`, { component: 'MonthSummary', wide: true }),
    cell('TransactionsList · day header and rows; swipe to delete', `${dayHead('Today', -36.36)}${txRow({ time: '11:16', title: 'Gasoline', category: 'Transit', value: 1000, currency: 'THB', base: 30.43 })}${txRow({ time: '08:25', title: 'Breakfast', category: 'Leisure', value: 160, currency: 'THB', base: 4.87 })}${dayHead('Yesterday', 2915.8)}${txRow({ time: '18:02', title: 'Groceries', category: 'Food & Drinks', value: 84.2, currency: 'USD' })}${txRow({ time: '09:00', title: 'Salary', category: 'Salary', value: 3000, currency: 'USD', income: true })}`, { component: 'TransactionsList', wide: true }),
    cell('EmptyState', `<div class="m-empty"><span class="m-well">${icon(ICON.RECEIPT, { size: 'xl', tone: 'textMuted' })}</span><div style="height:16px"></div>${text(L.EMPTY_TRANSACTIONS, { size: 'l', bold: true })}<div style="height:8px"></div>${text(L.EMPTY_TRANSACTIONS_CAPTION, { size: 's', tone: 'muted', center: true, style: 'max-width:250px' })}<div style="height:24px"></div>${btn(L.EMPTY_TRANSACTIONS_ACTION, { variant: 'outlined' })}</div>`, { component: 'EmptyState' }),
    cell('Notification · a band from the top', `<div class="m-notification accent">${icon(ICON.CHECK, { size: 'm' })}${text(L.CONFIRM_RATES_SUCCESS, { size: 's', medium: true, tone: 'onAccent' })}</div><div class="m-notification inverse">${icon(ICON.INFO)}${text(L.CONFIRM_EXPORT_SUCCESS, { size: 's', medium: true, tone: 'onInverse' })}</div><div class="m-notification danger">${icon(ICON.ALERT)}${text(L.ERROR_SERVICE_RATES, { size: 's', medium: true, tone: 'onInverse' })}</div>`, { component: 'Notification', stack: true, wide: true }),
    cell('Confirm · a dialog on the scrim', `<div style="padding:28px;background:var(--color-overlay)"><div class="m-dialog" style="border:var(--hairline) solid var(--color-rule);border-radius:0"><span class="m-well" style="width:44px;height:44px;background:var(--color-danger-soft)">${icon(ICON.ALERT, { size: 'l', tone: 'danger' })}</span>${text(L.CONFIRM_DELETION, { size: 'l', bold: true })}${text(L.CONFIRM_DELETION_CAPTION, { size: 's', tone: 'secondary', center: true })}<div class="actions">${btn(L.CANCEL, { variant: 'outlined', grow: true })}${btn(L.ACCEPT, { variant: 'danger', grow: true })}</div></div></div>`, { component: 'Confirm', wide: true }),
    cell('Modal · a bottom sheet with a drag to close', `<div style="padding:24px 0 0;background:var(--color-overlay)"><div style="background:var(--color-background);border-radius:4px 4px 0 0;padding:16px 20px 20px"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px">${text('September 2026', { medium: true })}${icon(ICON.DOWN, { size: 's', tone: 'textMuted' })}</div><div style="display:grid;grid-template-columns:repeat(7,1fr);gap:6px;text-align:center">${Array.from({ length: 21 }, (_, i) => fig(`${i + 1}`, { size: 'sm', tone: i === 8 ? 'onAccent' : undefined, style: i === 8 ? 'background:var(--color-accent);border-radius:4px;padding:4px 0' : 'padding:4px 0' })).join('')}</div></div></div>`, { component: 'Modal' }),
    cell('Panel · a pushed screen with a masthead and a floating add', `<div style="position:relative;height:160px;overflow:hidden">${masthead({ section: 'Chase', back: true, actions: btn(L.EDIT, { size: 's', variant: 'outlined' }) })}${seal(true)}</div>`, { component: 'Panel', wide: true }),
    cell('Screen · scrolls, pads 20 at the foot, keeps a focused field above the keyboard', `<div style="border:var(--hairline) dashed var(--color-border);padding:12px 20px 20px">${text('content', { size: 'xs', tone: 'muted' })}</div>`, { component: 'Screen' }),
    cell('IconButton', `<div style="display:flex;gap:8px">${iconButton(ICON.SEARCH)}${iconButton(ICON.ADD)}${iconButton(ICON.BACK)}${iconButton(ICON.CLOSE)}</div>`, { component: 'IconButton' }),
    cell('FloatingAdd · the seal, following you onto a panel', `<div style="position:relative;height:72px">${seal(true)}</div>`, { component: 'FloatingAdd' }),
    cell('Logo · the wordmark', logo(), { component: 'Logo' }),
    cell('Mark · the app icon inverts on fixed colours', `<div style="display:flex;gap:12px;align-items:flex-end">${mark(56)}${mark(44)}</div>`, { component: 'Mark' }),
    cell('Tabs · an accent or inverse tab strip', `<div style="display:flex;padding:4px;background:var(--color-border);border-radius:4px;gap:4px"><span style="padding:8px 16px;border-radius:4px;background:var(--color-accent)">${text('Expenses', { bold: true, tone: 'onAccent' })}</span><span style="padding:8px 16px">${text('Incomes', { bold: true })}</span></div>`, { component: 'Tabs' }),
    cell('ErrorBoundary · the fallback when a screen throws', `<div style="display:flex;flex-direction:column;align-items:center;gap:8px;padding:24px">${text(L.ERROR, { size: 'l', bold: true })}${text('Rendering failed in Overview', { size: 's', tone: 'secondary' })}${btn(L.ERROR_TRY_AGAIN)}</div>`, { component: 'ErrorBoundary' }),
  ];

  return page({
    file: 'index.html',
    title: 'Design system',
    intro: 'Paper and ink, one accent, figures in mono and hairlines instead of elevation. Every specimen on this page is drawn from the values in <code>src/theme</code> and the components in <code>src/components</code>, so what you see is what ships.',
    body: [
      section('Colour', `<div class="kit-grid wide">${colours}</div>`, 'Light and dark keep the same roles. Swatches read the live value of the theme you have selected above.'),
      section('Type', grid([cell('Copy · Euclid Circular A', copyRamp, { stack: true }), cell('Figures · Geist Mono, tabular, tracking −0.3', figureRamp, { stack: true }), cell('Weights and the eyebrow', weights)], true), 'Two ramps: one for copy, one for figures. Four text sizes multiply both; nothing else scales.'),
      section('Icons', grid([cell('Every glyph the app names, from src/modules/icon.js', `<div style="display:flex;flex-wrap:wrap;gap:12px 4px">${icons}</div>`, { wide: true })], true)),
      section('Space, radius, rules, motion', grid([cell('Spacing', spacing, { stack: true }), cell('Radius · three and no more', radii), cell('Rules · separation is a hairline', rules), cell('Motion', motion, { wide: true })], true)),
      section('Shared geometry', grid([cell('src/theme/layout.js', geometry, { wide: true })], true), 'Every size a row, a field or a card has is derived from the spacing scale, so the whole app moves when one number does.'),
      section('Primitives', grid(primitives, true)),
      section('Components', grid(components, true), 'One specimen per directory in <code>src/components</code>, in its resting state. Screens compose these and never restyle them in place.'),
    ].join('\n'),
  });
};

const CLAIMS = [1, 2, 3, 4].map((index) => [L[`ONB_CLAIM_${index}`], L[`ONB_CLAIM_${index}_CAPTION`]]);
const KEYPAD = [[1, ''], [2, 'ABC'], [3, 'DEF'], [4, 'GHI'], [5, 'JKL'], [6, 'MNO'], [7, 'PQRS'], [8, 'TUV'], [9, 'WXYZ'], ['bio', ''], [0, ''], ['del', '']];
const keypad = ({ biometric } = {}) =>
  `<div class="m-keypad">${KEYPAD.map(([key, letters]) => `<span class="m-key">${key === 'bio' ? (biometric ? icon(ICON.BIOMETRIC, { size: 'l' }) : '') : key === 'del' ? icon(ICON.BACKSPACE, { size: 'l', tone: 'textMuted' }) : `${fig(String(key), { size: 'xl' })}${eyebrow(letters || ' ')}`}</span>`).join('')}</div>`;
const pins = (filled, { accent } = {}) => `<div class="m-pins">${[0, 1, 2, 3].map((i) => `<span class="m-pin${i < filled ? ' on' : ''}" style="${accent ? 'border-color:var(--color-text-muted);width:14px;height:14px;border-width:1.5px' : ''}${accent && i < filled ? ';background:var(--color-accent);border-color:var(--color-accent)' : ''}"></span>`).join('')}</div>`;

const onboardingHead = (step) => `${masthead({ actions: `${eyebrow(L.ONB_SETUP)}${fig(`0${step} / 04`, { size: 'xs', tone: 'muted' })}`, rule: false })}`;
const stepTitle = (title, caption) => `<div style="padding-top:24px">${text(title, { size: 'xl', bold: true })}<div style="height:8px"></div>${text(caption, { size: 's', tone: 'secondary', style: 'display:block;max-width:300px' })}</div>`;
const onboardingFoot = (label, { note } = {}) => `<div style="margin-top:auto;padding:16px 20px;display:flex;flex-direction:column;gap:12px">${note ? text(note, { size: 'xs', tone: 'muted' }) : ''}${btn(label)}</div>`;

const ACCOUNTS = [
  { title: 'Chase', currency: 'USD', balance: 12480.55, change: 3.2 },
  { title: 'Wallet', currency: 'THB', balance: 34596, base: 1052.61 },
  { title: 'N26', currency: 'EUR', balance: 3210, base: 3720.44 },
  { title: 'Cold wallet', currency: 'BTC', balance: 0.52, base: 42197.14 },
];
const NET = 61648.74;
const netEyebrow = () => `${L.NET_WORTH} · ${ACCOUNTS.length} ${L.ACCOUNTS_CAPTION(ACCOUNTS.length)} · ${BASE}`;

const overviewBody = () =>
  content(`<div class="m-hero">${eyebrow(netEyebrow())}<div style="margin-top:4px">${price(NET, { size: 'hero', bold: true })}</div><div class="meta">${delta(3.2, { caption: L.THIS_MONTH_CAPTION })}</div></div><div class="m-section">${heading(L.THIS_MONTH, { eyebrow: 'September' })}${monthSummary({ spent: 552.78, baseline: 1042.29, pace: `−47% ${L.BELOW_PACE}`, day: 9, swing: -208.11, swingCategory: 'Personal', scheduled: 1325.29, pending: 4 })}</div><div class="m-section">${heading(L.ACCOUNTS, { actions: eyebrow(L.SEE_ALL_COUNT(ACCOUNTS.length)) })}${ACCOUNTS.slice(0, 3).map(accountRow).join('')}</div><div class="m-section">${heading(L.TRANSACTIONS, { actions: eyebrow(L.SEE_ALL) })}${dayHead('Today', -36.36)}${txRow({ time: '11:16', title: 'Gasoline', category: 'Transit', value: 1000, currency: 'THB', base: 30.43 })}${txRow({ time: '08:25', title: 'Breakfast', category: 'Leisure', value: 160, currency: 'THB', base: 4.87 })}</div>`);

const mobile = () => {
  counter = 0;
  const boards = {
    onboarding: [
      phone('Onboarding', 'Onboarding · cover', `${onboardingHead(1)}${content(`<div style="padding-top:36px">${mark(56)}<div style="height:32px"></div>${text(L.ONB_COVER_TITLE, { size: 'xxl', bold: true })}<div style="height:8px"></div>${text(L.ONB_COVER_CAPTION, { size: 's', tone: 'secondary', style: 'display:block;max-width:300px' })}</div><div style="margin-top:20px">${heading(L.ONB_COVER_HEADING, { eyebrow: L.ONB_COVER_HEADING_EYEBROW })}${CLAIMS.map(([claim, caption], index) => `<div style="display:flex;gap:8px;padding:9px 0${index ? ';border-top:var(--hairline) solid var(--color-border)' : ''}"><span style="width:18px">${fig(`0${index + 1}`, { size: 'xs', tone: 'muted' })}</span><span style="flex:1">${text(claim, { medium: true })}<br>${text(caption, { size: 'xs', tone: 'muted' })}</span></div>`).join('')}</div>`)}${onboardingFoot(L.ONB_START)}`),
      phone('Onboarding', 'Onboarding · currency', `${onboardingHead(2)}${content(`${stepTitle(L.ONB_CURRENCY_TITLE, L.ONB_CURRENCY_CAPTION)}${C.CURRENCY_GROUPS.slice(0, 2).map(({ codes, id }, group) => `<div style="margin-top:${group ? 16 : 20}px">${eyebrow(L.CURRENCY_GROUP[id] || id, { style: 'display:block;margin-bottom:8px' })}${codes.slice(0, group ? 3 : 6).map((code, index) => `<div style="display:flex;align-items:center;gap:12px;height:44px${index ? ';border-top:var(--hairline) solid var(--color-border)' : ''}"><span class="m-well s" style="background:var(--color-surface)">${fig(C.SYMBOL[code], { size: 'sm' })}</span><span style="flex:1">${text(code, { medium: true })}<br>${text(L.CURRENCY_NAME[code] || code, { size: 'xxs', tone: 'muted' })}</span>${code === 'USD' ? icon(ICON.CHECK, { tone: 'accent' }) : fig(['0.86', '148.2', '0.75', '0.80', '7.13', '1.36', '5.42', '18.6'][index % 8], { size: 'xs', tone: 'muted' })}</div>`).join('')}</div>`).join('')}`)}${onboardingFoot(L.CONTINUE, { note: L.ONB_CURRENCY_NOTE })}`),
      phone('Onboarding', 'Onboarding · first account', `${onboardingHead(3)}${content(`${stepTitle(L.ONB_ACCOUNT_TITLE, L.ONB_ACCOUNT_CAPTION)}<div style="margin-top:20px">${fieldRow(L.NAME, input('Chase', { right: true }))}${fieldRow(L.CURRENCY, text('USD · US Dollar', { size: 's', medium: true }), { divider: true, chevron: true })}${fieldRow(L.BALANCE, `${input('12480.55', { right: true, figure: true })}${fig('$', { size: 'sm', tone: 'muted' })}`, { divider: true })}</div><div style="display:flex;gap:8px;margin-top:16px">${icon(ICON.INFO, { size: 'xs', tone: 'textMuted' })}${text(L.ONB_ACCOUNT_NOTE, { size: 'xs', tone: 'muted' })}</div>`)}${onboardingFoot(L.CONTINUE)}`),
      phone('Onboarding', 'Onboarding · passcode', `${onboardingHead(4)}${content(`${stepTitle(L.ONB_PIN_TITLE, L.ONB_PIN_CAPTION)}${pins(2)}${keypad()}`)}`),
    ],
    session: phone('Session', 'Lock screen · PIN with the biometric key', `<div style="flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px;padding-bottom:24px"><div style="flex:1.2"></div><span class="m-logo" style="font-size:24px;letter-spacing:3.5px">MÔNEY</span>${text(L.PIN, { size: 's', tone: 'muted' })}${pins(2, { accent: true })}<div style="flex:1"></div><div style="width:100%">${keypad({ biometric: true })}</div>${text(`môney v${VERSION}`, { size: 'xxs', tone: 'muted' })}</div>`),
    overview: phone('Dashboard', 'Overview · the month against the usual', `${masthead({ section: 'Wed 9 Sep 2026', actions: iconButton(ICON.SEARCH) })}${overviewBody()}`, { tab: L.OVERVIEW }),
    overviewFold: phone('Dashboard', 'Overview on the Fold · the same layout, wider', `${masthead({ section: 'Wed 9 Sep 2026', actions: iconButton(ICON.SEARCH) })}${overviewBody()}`, { tab: L.OVERVIEW, fold: true }),
    accounts: phone('Accounts', 'Accounts · distribution and a currency filter', `${masthead({ section: L.ACCOUNTS, actions: iconButton(ICON.ADD) })}${content(`<div class="m-hero">${eyebrow(netEyebrow())}<div style="margin-top:4px">${price(NET, { size: 'hero', bold: true })}</div></div><div style="margin-top:12px"><div class="m-dist" style="height:10px">${[[68, 'accent'], [20, 'text'], [7, 'text-secondary'], [5, 'text-muted']].map(([w, c]) => `<i style="flex-grow:${w};background:var(--color-${c})"></i>`).join('')}</div><div class="m-legend">${[['BTC', 68, 'accent'], ['USD', 20, 'text'], ['EUR', 7, 'text-secondary'], ['THB', 5, 'text-muted']].map(([code, pct, c]) => `<span><i class="m-dot" style="background:var(--color-${c})"></i>${text(code, { size: 'xxs', medium: code === BASE, tone: code === BASE ? undefined : 'muted' })}${fig(`${pct}%`, { size: 'xs', tone: 'muted' })}</span>`).join('')}</div></div><div style="margin-top:16px">${seg([L.ALL, 'BTC', 'THB', 'EUR', 'USD'], L.ALL, { auto: true })}</div><div class="m-section">${heading(L.ACCOUNTS, { eyebrow: `${ACCOUNTS.length}` })}${ACCOUNTS.map((account) => accountRow({ ...account, change: undefined })).join('')}<div style="display:flex;justify-content:space-between;align-items:baseline;padding-top:12px">${eyebrow(L.TOTAL)}<span class="amount">${price(NET, { size: 'lg', bold: true })}</span></div></div>`)}`, { tab: L.ACCOUNTS }),
    transactions: phone('Transactions', 'Transactions · one account, a floating add', `${masthead({ section: 'Wallet', back: true, actions: btn(L.EDIT, { size: 's', variant: 'outlined' }) })}${content(`<div class="m-hero">${eyebrow(`${L.ACCOUNT_BALANCE} · THB`)}<div style="margin-top:4px">${price(34596, { currency: 'THB', size: 'hero', bold: true, symbol: true })}</div><div class="meta">${delta(-4.7, { caption: L.THIS_MONTH_CAPTION })}</div></div><div style="margin-top:16px;padding-top:12px;border-top:var(--hairline) solid var(--color-border)">${eyebrow('September', { style: 'display:block;margin-bottom:8px' })}<div class="m-flow"><span class="label">${text(L.INCOMES, { size: 's', tone: 'muted' })}</span><span class="track"><i style="display:block;width:100%;height:100%;background:var(--color-accent)"></i></span><span class="value">${price(40000, { currency: 'THB', operator: true, symbol: true })}</span></div><div class="m-flow"><span class="label">${text(L.EXPENSES, { size: 's', tone: 'muted' })}</span><span class="track"><i style="display:block;width:31%;height:100%;background:var(--color-text)"></i></span><span class="value">${price(-12270, { currency: 'THB', symbol: true })}</span></div></div>${dayHead('Today', -36.36)}${txRow({ time: '11:16', title: 'Gasoline', category: 'Transit', value: 1000, currency: 'THB', base: 30.43 })}${txRow({ time: '08:25', title: 'Breakfast', category: 'Leisure', value: 160, currency: 'THB', base: 4.87 })}${txRow({ time: '07:07', title: 'Nuts', category: 'Food & Drinks', value: 20, currency: 'THB', base: 0.61 })}${dayHead('Yesterday', -107.16)}${txRow({ time: '19:34', title: 'Bread', category: 'Food & Drinks', value: 40, currency: 'THB', base: 1.22 })}${txRow({ time: '14:58', title: 'Water', category: 'Home', value: 101, currency: 'THB', base: 3.07 })}`)}${seal(true)}`),
    transaction: phone('Transaction', 'Transaction · an expense with two proposals', `${masthead({ section: L.TRANSACTION, sheet: true })}${content(`<div style="margin-top:8px">${seg([L.EXPENSE, L.INCOME, L.SWAP], L.EXPENSE)}</div><div style="margin-top:16px">${fieldRow(L.CONCEPT, input('coff', { right: true }))}${fieldRow('', `${text('Coffee', { size: 's', medium: true })}${text('Wallet', { size: 'xs', tone: 'muted' })}${price(65, { currency: 'THB', tone: 'accent' })}`, { divider: true })}${fieldRow('', `${text('Coffee beans', { size: 's', medium: true })}${text('Wallet', { size: 'xs', tone: 'muted' })}${price(1355, { currency: 'THB', tone: 'accent' })}`, { divider: true })}${fieldRow(L.AMOUNT, `${input('', { placeholder: '0', right: true, figure: true })}${fig('฿', { size: 'sm', tone: 'muted' })}`, { divider: true })}${fieldRow(L.ACCOUNT, `${text('Wallet ·', { size: 's', medium: true })}${price(34596, { currency: 'THB', symbol: true })}`, { divider: true, chevron: true })}${fieldRow(L.CATEGORY, text('Food & Drinks', { size: 's', medium: true }), { divider: true, chevron: true })}<div class="m-checkrow">${text(L.HIDE_FROM_ANALYTICS, { size: 's', tone: 'muted' })}${check(false)}</div>${fieldRow(L.DATE, text('Today, Sep 9', { size: 's', medium: true }), { divider: true, chevron: true })}</div><div style="margin-top:24px">${btn(L.SAVE_EXPENSE, { disabled: true, grow: true })}</div>`)}`, { sheet: true }),
    swap: phone('Transaction', 'Transaction · a swap between own accounts', `${masthead({ section: L.TRANSACTION, sheet: true })}${content(`<div style="margin-top:8px">${seg([L.EXPENSE, L.INCOME, L.SWAP], L.SWAP)}</div><div style="margin-top:16px">${fieldRow(L.FROM_ACCOUNT, `${text('Chase ·', { size: 's', medium: true })}${price(12480.55)}`, { chevron: true })}${fieldRow(L.SEND, `${input('500', { right: true, figure: true })}${fig('$', { size: 'sm', tone: 'muted' })}`, { divider: true })}${fieldRow(L.DESTINATION, `${text('Wallet ·', { size: 's', medium: true })}${price(34596, { currency: 'THB', symbol: true })}`, { divider: true, chevron: true })}${fieldRow(L.RECEIVE, `${input('16430', { right: true, figure: true })}${fig('฿', { size: 'sm', tone: 'muted' })}`, { divider: true })}</div><div style="margin-top:24px">${btn(L.SAVE_SWAP, { grow: true })}</div>`)}`, { sheet: true }),
    clone: phone('Clone', 'Clone · edit, duplicate or delete an entry', `${masthead({ section: L.EXPENSE, sheet: true })}${content(`<div class="m-suggest">${chip(`${L.SUGGESTED}: Home`, { variant: 'soft', iconRight: ICON.CLOSE })}</div><div>${fieldRow(L.CONCEPT, input('Water', { right: true }))}${fieldRow(L.AMOUNT, `${input('101', { right: true, figure: true })}${fig('฿', { size: 'sm', tone: 'muted' })}`, { divider: true })}${fieldRow(L.ACCOUNT, `${text('Wallet ·', { size: 's', medium: true })}${price(34596, { currency: 'THB', symbol: true })}`, { divider: true, chevron: true })}${fieldRow(L.CATEGORY, text('Home', { size: 's', medium: true }), { divider: true, chevron: true })}<div class="m-checkrow">${text(L.HIDE_FROM_ANALYTICS, { size: 's', tone: 'muted' })}${check(false)}</div>${fieldRow(L.DATE, text('Yesterday, Sep 8', { size: 's', medium: true }), { divider: true, chevron: true })}</div><div style="display:flex;gap:12px;margin-top:24px">${btn(L.DELETE, { variant: 'dangerSoft', grow: true })}${btn(L.DUPLICATE, { variant: 'outlined', grow: true, disabled: true })}${btn(L.SAVE, { grow: true })}</div>`)}`, { sheet: true }),
    scheduled: phone('Scheduled', 'Scheduled · templates by when they fall', `${masthead({ section: L.SCHEDULED, back: true, actions: btn('', { variant: 'outlined', iconName: ICON.ADD }) })}${content(`<div style="padding:12px 0 8px">${eyebrow(`${L.SCHEDULED_IMPACT} · ${BASE}`)}<div style="margin:4px 0">${price(1325.29, { size: 'xl', bold: true, operator: true })}</div>${text(L.SCHEDULED_IMPACT_CAPTION, { size: 'xxs', tone: 'muted' })}</div>${[[L.SCHEDULED_SECTION_UPCOMING, [['Fri', 'Sep 12', 'Rent', 'Monthly · day 12', -1200, 'USD'], ['Mon', 'Sep 15', 'Salary', 'Monthly · day 15', 3000, 'USD']]], [L.SCHEDULED_SECTION_MONTH, [['Thu', 'Sep 25', 'Gym', 'Weekly · Thu', -40, 'USD'], ['Tue', 'Sep 30', 'Internet', 'Monthly · day 30', -434.71, 'USD']]]].map(([title, rows]) => `<div style="margin-top:16px">${eyebrow(title, { style: 'display:block;margin-bottom:6px' })}${rows.map(([wd, date, name, rule, value, currency]) => `<div class="m-row" style="padding:10px 0"><span style="width:56px">${eyebrow(wd)}<br>${fig(date, { size: 'xs', tone: 'muted' })}</span><span class="text">${text(name, { medium: true })}${text(rule, { size: 'xxs', tone: 'muted' })}</span><span class="amount">${price(value, { currency, size: 'md', bold: true, operator: true, symbol: true })}</span></div>`).join('')}</div>`).join('')}`)}`),
    scheduledForm: phone('ScheduledForm', 'Scheduled form · a weekly rule', `${masthead({ section: L.SCHEDULED_ONE, sheet: true })}${content(`<div style="margin-top:8px">${seg([L.EXPENSE, L.INCOME], L.EXPENSE)}</div><div style="margin-top:16px">${fieldRow(L.CONCEPT, input('Gym', { right: true }))}${fieldRow(L.AMOUNT, `${input('40', { right: true, figure: true })}${fig('$', { size: 'sm', tone: 'muted' })}`, { divider: true })}${fieldRow(L.ACCOUNT, text('Chase', { size: 's', medium: true }), { divider: true, chevron: true })}${fieldRow(L.CATEGORY, text('Healthcare', { size: 's', medium: true }), { divider: true, chevron: true })}</div><div style="margin-top:20px">${eyebrow(L.SCHEDULED_FREQUENCY, { style: 'display:block;margin-bottom:8px' })}${seg([L.SCHEDULED_PATTERN_WEEKLY, L.SCHEDULED_PATTERN_MONTHLY], L.SCHEDULED_PATTERN_WEEKLY)}</div><div class="m-daychips" style="margin-top:12px">${['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((d, i) => `<span class="m-daychip${i === 3 ? ' on' : ''}">${text(d, { size: 's', bold: i === 3, medium: i !== 3, tone: i === 3 ? 'onAccent' : 'muted' })}</span>`).join('')}</div><div style="margin-top:12px">${text('Next · Thu, 11 Sep', { size: 's', tone: 'muted' })}</div><div style="display:flex;gap:12px;margin-top:24px">${btn(L.DELETE, { variant: 'dangerSoft', grow: true })}${btn(L.SAVE, { grow: true })}</div>`)}`, { sheet: true }),
    stats: phone('Stats', 'Analytics · balance, cash flow, the month, categories', `${masthead({ section: L.ACTIVITY, actions: seg(['6M', '1Y', L.RANGE_ALL], '1Y', { compact: true }) })}${content(`<div style="margin-top:16px">${eyebrow(netEyebrow())}<div style="display:flex;align-items:baseline;gap:8px;margin-top:4px">${price(NET, { size: 'hero', bold: true })}${delta(7.2, { caption: L.STATS_RANGE_1Y_CAPTION })}</div>${chart({ values: [48, 51, 47, 52, 56, 55, 58, 54, 57, 60, 59, 61.6], trend: [47, 48.5, 49, 50, 51.5, 53, 54.5, 55, 56, 57.5, 58.5, 59.5], labels: ['Oct', 'Dec', 'Feb', 'Apr', 'Jun', 'Sep'], pointer: 11 })}</div><div style="margin-top:16px">${heading(L.CASHFLOW)}${flowChart({ incomes: [3000, 3000, 3200, 3000, 4100, 3000], expenses: [2100, 2450, 1980, 2600, 2300, 552], labels: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'], selected: 5 })}</div><div style="margin-top:16px">${heading('September', { eyebrow: L.MONTH_TO_DATE })}<div class="m-kpis"><span class="kpi">${eyebrow(L.FLOW_IN)}${price(3000, { operator: true })}</span><span class="kpi">${eyebrow(L.FLOW_OUT)}${price(-552.78)}</span><span class="kpi">${eyebrow(L.NET)}${price(2447.22, { operator: true })}</span></div></div><div style="margin-top:4px">${heading(L.EXPENSES, { eyebrow: 'September' })}${[['Personal', 41, 226], ['Transit', 22, 121], ['Food & Drinks', 19, 105], ['Leisure', 11, 61], [`${L.OTHERS} · 3`, 7, 39]].map(([name, pct, value], index) => `<div class="m-category"><i class="m-dot" style="width:9px;height:9px;background:${index < 4 ? `var(--color-${kebab(['accent', 'text', 'textSecondary', 'textMuted'][index])})` : 'var(--color-text-muted)'}"></i><span style="flex:1">${text(name, { size: 's' })}</span><span class="track" style="max-width:96px"><i class="fill" style="display:block;width:${pct}%;background:${index < 4 ? `var(--color-${kebab(['accent', 'text', 'textSecondary', 'textMuted'][index])})` : 'var(--color-text-muted)'}"></i></span>${fig(`${pct}%`, { size: 'xs', tone: 'muted', style: 'min-width:34px;text-align:right' })}${price(value, { fixed: 0, bold: true })}</div>`).join('')}</div>`)}`, { tab: L.ACTIVITY }),
    category: phone('Category', 'Category · where it went', `${masthead({ section: 'Personal', sheet: true })}${content(`<div style="display:flex;align-items:center;gap:8px;padding-top:4px"><i class="m-dot" style="width:9px;height:9px;background:var(--color-accent)"></i>${text('Personal', { size: 'l', bold: true, style: 'flex:1' })}${eyebrow(`September · ${BASE}`)}</div><div style="display:flex;align-items:baseline;gap:8px;margin-top:8px">${price(226, { size: 'xl', bold: true })}${fig(`41% ${L.OF_SPEND}`, { size: 'sm', tone: 'muted' })}</div><div style="display:flex;align-items:baseline;gap:8px;margin-top:4px">${delta(-12, { plain: true, inverted: true, places: 0 })}${text(L.VS_YOUR_AVERAGE(6), { size: 'xs', tone: 'muted' })}${price(257.4, { size: 'xs', tone: 'muted' })}</div><div style="margin-top:20px">${heading(L.WHERE_IT_WENT, { eyebrow: `3 ${L.MERCHANTS}` })}${[['Coffee', 9, 180, 100], ['Barber', 1, 30, 17], ['Pharmacy', 2, 16, 9]].map(([name, count, value, w]) => `<div class="m-merchant">${text(name, { medium: true, style: 'flex:1' })}<span class="track"><i class="fill" style="display:block;width:${w}%"></i></span>${fig(`${count} ×`, { size: 'xs', tone: 'muted', style: 'min-width:30px;text-align:right' })}<span style="min-width:72px;text-align:right">${price(value)}</span></div>`).join('')}</div><div style="margin-top:20px">${heading(L.LATEST, { actions: eyebrow(L.SEE_ALL_COUNT(12)) })}${[['Sep 8', 'Coffee', 'Wallet', -1.98], ['Sep 6', 'Coffee', 'Wallet', -1.98], ['Sep 4', 'Barber', 'Chase', -30]].map(([date, name, account, value]) => `<div class="m-merchant">${fig(date, { size: 'xs', tone: 'muted', style: 'min-width:40px' })}<span style="flex:1">${text(name, { medium: true })}<br>${text(account, { size: 'xxs', tone: 'muted' })}</span>${price(value)}</div>`).join('')}</div>`)}`, { sheet: true }),
    account: phone('Account', 'Account · currency, opening balance, name', `${masthead({ section: L.ACCOUNTS, sheet: true })}${content(`<div style="margin-top:8px">${heading(L.DETAILS)}</div><div style="margin-top:12px">${fieldRow(L.CURRENCY, `<span style="display:flex;align-items:center;gap:12px;flex:1"><span class="m-well s">${fig('฿', { size: 'sm' })}</span>${text('THB · Thai Baht', { medium: true, style: 'flex:1' })}${icon(ICON.DOWN, { size: 's', tone: 'textMuted' })}</span>`)}${fieldRow(L.INITIAL_BALANCE, `${input('34596', { right: true, figure: true })}${price(1052.61, { size: 'sm', tone: 'secondary' })}`, { divider: true })}${fieldRow(L.NAME, input('Wallet', { right: true }), { divider: true })}</div><div style="display:flex;gap:12px;margin-top:24px">${btn(L.DELETE, { variant: 'dangerSoft', grow: true })}${btn(L.CANCEL, { variant: 'outlined', grow: true })}${btn(L.SAVE, { grow: true })}</div>`)}`, { sheet: true }),
    settings: phone('Settings', 'Settings · with the weekly backup nudge', `${masthead({ section: L.SETTINGS })}${content(`<div class="m-band" style="margin:12px -20px 0;border-radius:0;padding:14px 20px">${icon(ICON.ALERT, { tone: 'onAccentSoft' })}<span style="flex:1">${text(L.EXPORT_DATA, { size: 's', medium: true, tone: 'onAccentSoft' })}<br>${text(`${L.BACKUP_LAST} · 9 days ago`, { size: 'xxs', tone: 'onAccentSoft' })}</span>${chip(L.BACKUP_CTA, { variant: 'inverse', size: 's' })}</div><div class="m-group">${eyebrow(L.DATA, { style: 'display:block' })}${setting(L.SYNC_RATES_CTA, { right: rightValue('2 h ago', { figure: true }) })}${setting(L.EXPORT_DATA, { divider: true, right: rightValue('9 days ago', { figure: true }) })}${setting(L.IMPORT_DATA, { divider: true, right: chevronRight() })}${setting(L.EXPORT_CSV, { divider: true, right: chevronRight() })}</div><div class="m-group">${eyebrow(L.APPEARANCE, { style: 'display:block' })}${setting(L.THEME, { right: `${text(L.APPEARANCE_SYSTEM, { size: 's', tone: 'muted' })}${icon(ICON.DOWN, { size: 's', tone: 'textMuted' })}` })}${setting(L.TEXT_SIZE, { divider: true, right: `${text(L.TEXT_SIZE_DEFAULT, { size: 's', tone: 'muted' })}${icon(ICON.DOWN, { size: 's', tone: 'textMuted' })}` })}</div><div class="m-group">${eyebrow(L.PREFERENCES, { style: 'display:block' })}${setting(L.LANGUAGE, { right: `${text('English', { size: 's', tone: 'muted' })}${icon(ICON.DOWN, { size: 's', tone: 'textMuted' })}` })}${setting(L.CHOOSE_CURRENCY, { divider: true, right: `${text('US Dollar', { size: 's', tone: 'muted' })}${icon(ICON.DOWN, { size: 's', tone: 'textMuted' })}` })}${setting(L.SCHEDULED, { divider: true, right: rightValue('4') })}${setting(L.REMINDER_BACKUP, { divider: true, subtitle: `${L.SCHEDULED_PATTERN_WEEKLY} - Sun 08:00`, right: switchEl(true) })}</div><div class="m-group">${eyebrow(L.UNLOCK, { style: 'display:block' })}${setting(L.BIOMETRIC_UNLOCK, { right: switchEl(false) })}</div><div class="m-group">${eyebrow(L.ABOUT, { style: 'display:block' })}${setting(L.TERMS)}${setting(L.PRIVACY, { divider: true })}${setting(L.SECURITY, { divider: true })}</div><div class="m-group">${eyebrow(L.ACCOUNT_ACTIONS, { style: 'display:block' })}${setting(L.LOG_OUT)}${setting(L.RESET_DATA, { divider: true, tone: 'danger' })}</div><div class="m-colophon">${eyebrow(`v${VERSION}`)}<span class="rule"></span>${eyebrow(C.MAKER_NAME)}${text(L.COLOPHON_TITLE, { size: 'l', bold: true, center: true })}${text(L.COLOPHON_CAPTION, { size: 'xs', tone: 'secondary', center: true })}${text(L.COLOPHON_WHO, { size: 'xs', tone: 'muted', center: true })}${fig(L.COLOPHON_VITALS, { size: 'xs', tone: 'muted' })}${text(C.MAKER_EMAIL, { size: 'xs', tone: 'accent' })}</div>`)}`, { tab: L.SETTINGS }),
  };

  return page({
    file: 'mobile.html',
    title: 'Mobile',
    intro: 'Every screen of the app at 390 points, phone and Fold in one layout. The boards are drawn with the same classes as the System page, from the same tokens, with a ledger that belongs to no one.',
    body: [
      section('Arrival', `<div class="kit-boards">${boards.onboarding.join('')}${boards.session}</div>`, 'Four steps with a folio, then the lock screen every open passes through.'),
      section('Tabs', `<div class="kit-boards">${boards.overview}${boards.accounts}${boards.stats}${boards.settings}</div>`, 'Overview, Accounts, Analytics and Settings sit under the footer; the seal in the middle opens a new expense.'),
      section('Panels and sheets', `<div class="kit-boards">${boards.transactions}${boards.scheduled}${boards.transaction}${boards.swap}${boards.clone}${boards.scheduledForm}${boards.category}${boards.account}</div>`, 'Panels push with the name in the wordmark\'s slot; forms rise as native sheets on the surface colour, sized from the tokens.'),
      section('The Fold', `<div class="kit-boards">${boards.overviewFold}</div>`, 'No second layout: the phone\'s columns stretch to the open Fold, and the figures keep their ramp.'),
    ].join('\n'),
  });
};

const parseRoadmap = () => {
  const lanes = {};
  let lane;
  let group;
  let entry;
  const source = read('ROADMAP.md');
  for (const line of source.slice(source.indexOf('\n## Queue')).split('\n')) {
    const h2 = line.match(/^## (.+)$/);
    if (h2) {
      lane = h2[1].replace(/ —.*$/, '');
      lanes[lane] = { entries: [], rows: [] };
      group = undefined;
      entry = undefined;
      continue;
    }
    if (!lane) continue;
    const h3 = line.match(/^### (.+)$/);
    if (h3) {
      group = h3[1];
      continue;
    }
    const head = line.match(/^- \*\*([A-Z][A-Z0-9-]+)\*\* — (.+)$/);
    if (head) {
      entry = { id: head[1], title: head[2], group, meta: '', accept: '' };
      lanes[lane].entries.push(entry);
      continue;
    }
    if (entry && /^\s{2}`/.test(line)) entry.meta = line.trim().replace(/`/g, '');
    else if (entry && /^\s{2}accept: /.test(line)) entry.accept = line.trim().slice(8);
    else if (entry && /^\s{2}\S/.test(line) && entry.accept) entry.accept += ` ${line.trim()}`;
    else if (line.startsWith('| ') && !line.startsWith('| Decision') && !line.startsWith('| ---')) {
      lanes[lane].rows.push(line.split('|').slice(1, -1).map((cell) => cell.trim()));
    }
  }
  return lanes;
};

const frame = (body, { sheet, width = 350 } = {}) => `<div class="m" style="width:${width}px;padding:12px 0;background:var(--color-${sheet ? 'surface' : 'background'})">${body}</div>`;
const miniMasthead = (section, actions = '') => `<div class="m-masthead" style="padding:0">${logo()}<span class="right">${eyebrow(section)}${actions}</span></div><div class="m-rule"></div>`;

const REVIEW = [
  {
    id: 'UX-SWING-COPY', area: 'Overview', title: 'A swing without a direction',
    why: 'The value is the category\'s spend minus its usual to date, but the hint is only the category name; the creator himself asked what the line meant.',
    now: frame(`<div style="display:flex;align-items:baseline;gap:8px;padding:7px 0;border-bottom:var(--hairline) solid var(--color-border)"><span style="width:96px">${text(L.SWING, { size: 's', tone: 'muted' })}</span><span style="flex:1">${price(-208.11)}</span>${text('Personal', { size: 'xs', tone: 'muted' })}</div>`),
    proposed: frame(`<div style="display:flex;align-items:baseline;gap:8px;padding:7px 0;border-bottom:var(--hairline) solid var(--color-border)"><span style="width:96px">${text(L.SWING, { size: 's', tone: 'muted' })}</span><span style="flex:1">${price(-208.11)}</span>${text(`Personal, ${L.BELOW_USUAL}`, { size: 'xs', tone: 'muted' })}</div>`),
  },
  {
    id: 'UX-PROPOSAL-ROW', area: 'Transaction', title: 'Proposals in a row built for a label',
    why: 'Each proposal is a FieldRow with label="", so 96 points sit empty on the left and the offer reads as a value with no key.',
    now: frame(`${fieldRow(L.CONCEPT, input('coff', { right: true }))}${fieldRow('', `${text('Coffee', { size: 's', medium: true })}${text('Wallet', { size: 'xs', tone: 'muted' })}${price(65, { currency: 'THB', tone: 'accent' })}`, { divider: true })}${fieldRow('', `${text('Coffee beans', { size: 's', medium: true })}${text('Wallet', { size: 'xs', tone: 'muted' })}${price(1355, { currency: 'THB', tone: 'accent' })}`, { divider: true })}`, { sheet: true }),
    proposed: frame(`${fieldRow(L.CONCEPT, input('coff', { right: true }))}${[['Coffee', 65], ['Coffee beans', 1355]].map(([title, value]) => `<div style="display:flex;align-items:center;gap:8px;min-height:44px;border-top:var(--hairline) solid var(--color-border)"><span style="flex:1">${text(title, { size: 's', medium: true })}<br>${text('Wallet · Personal', { size: 'xxs', tone: 'muted' })}</span>${price(value, { currency: 'THB', tone: 'accent', symbol: true })}</div>`).join('')}`, { sheet: true }),
  },
  {
    id: 'UX-FOLD-WIDTH', area: 'The Fold', title: 'One column across 720 points',
    why: 'No layout maxWidth exists; rows, forms and the keypad (keys at 33.333%) stretch with the window.',
    now: `<div class="m" style="width:520px;padding:12px 0;background:var(--color-background)">${miniMasthead('Wed 9 Sep 2026')}${accountRow(ACCOUNTS[0])}${accountRow(ACCOUNTS[1])}<div class="m-keypad" style="padding:12px 0 0">${[1, 2, 3].map((k) => `<span class="m-key" style="height:48px">${fig(String(k), { size: 'xl' })}</span>`).join('')}</div></div>`,
    proposed: `<div class="m" style="width:520px;padding:12px 0;background:var(--color-background)">${miniMasthead('Wed 9 Sep 2026')}<div style="max-width:390px;margin:0 auto">${accountRow(ACCOUNTS[0])}${accountRow(ACCOUNTS[1])}<div class="m-keypad" style="padding:12px 0 0">${[1, 2, 3].map((k) => `<span class="m-key" style="height:48px">${fig(String(k), { size: 'xl' })}</span>`).join('')}</div></div></div>`,
  },
  {
    id: 'UX-SETTINGS-CASE', area: 'Settings', title: 'Title Case on one screen',
    why: 'Every other screen is sentence case; Settings rows arrived capitalised word by word.',
    now: frame(`${setting('Update Rates', { right: rightValue('2 h ago', { figure: true }) })}${setting('Backup Data', { divider: true, right: chevronRight() })}${setting('Restore Data', { divider: true, right: chevronRight() })}${setting('Base Currency', { divider: true, right: rightValue('US Dollar') })}${setting('Backup Reminder', { divider: true, right: switchEl(true) })}${setting('Privacy Policy', { divider: true })}`),
    proposed: frame(`${setting('Update rates', { right: rightValue('2 h ago', { figure: true }) })}${setting('Back up data', { divider: true, right: chevronRight() })}${setting('Restore data', { divider: true, right: chevronRight() })}${setting('Base currency', { divider: true, right: rightValue('US Dollar') })}${setting('Backup reminder', { divider: true, right: switchEl(true) })}${setting('Privacy policy', { divider: true })}`),
  },
  {
    id: 'UX-LOCK-COPY', area: 'Settings', title: '"Log out" of an app with no account',
    why: 'The action resets to the lock screen; the copy, and its translations (Déconnexion, Abmelden), promise an account that does not exist.',
    now: frame(`${setting(L.LOG_OUT)}<div style="height:12px"></div><div class="m-dialog" style="border:var(--hairline) solid var(--color-rule);padding:16px">${text(L.CONFIRM_LOG_OUT, { size: 'l', bold: true })}${text(L.CONFIRM_LOG_OUT_CAPTION, { size: 's', tone: 'secondary', center: true })}</div>`),
    proposed: frame(`${setting('Lock')}<div style="height:12px"></div><div class="m-dialog" style="border:var(--hairline) solid var(--color-rule);padding:16px">${text('Lock Môney?', { size: 'l', bold: true })}${text('You will be asked for your PIN. Your data stays on this phone.', { size: 's', tone: 'secondary', center: true })}</div>`),
  },
  {
    id: 'UX-ADD-CONTROLS', area: 'Accounts · Scheduled', title: 'Three shapes for the same verb',
    why: 'Accounts adds with an IconButton, Scheduled with an outlined Button carrying the icon, and transactions with the seal.',
    now: frame(`<div style="display:flex;gap:16px;align-items:center">${iconButton(ICON.ADD)}${btn('', { variant: 'outlined', iconName: ICON.ADD })}${seal()}</div><div style="margin-top:10px">${text('Accounts masthead · Scheduled masthead · transactions', { size: 'xxs', tone: 'muted' })}</div>`),
    proposed: frame(`<div style="display:flex;gap:16px;align-items:center">${iconButton(ICON.ADD)}${iconButton(ICON.ADD)}${seal()}</div><div style="margin-top:10px">${text('every masthead that adds · the seal only for a transaction', { size: 'xxs', tone: 'muted' })}</div>`),
  },
  {
    id: 'UX-MASK-AFFORDANCE', area: 'Overview · Settings', title: 'A hidden tap masks every amount',
    why: 'Tapping the net-worth hero toggles maskAmount; nothing on the screen says so, and nothing in Settings shows the state.',
    now: frame(`${eyebrow(netEyebrow())}<div style="margin-top:4px">${price(NET, { size: 'hero', bold: true, masked: true })}</div>${text('(tap the figure)', { size: 'xxs', tone: 'muted' })}`),
    proposed: frame(`${eyebrow(L.PREFERENCES, { style: 'display:block;margin-bottom:4px' })}${setting('Mask amounts', { subtitle: 'Also toggled by tapping the net worth', right: switchEl(true) })}`),
  },
  {
    id: 'UX-CHIP-TARGET', area: 'Transaction', title: 'A 24-point tap target',
    why: 'The suggestion chip is size xs (minHeight 24) and dismisses on press; the platform guideline is 44.',
    now: frame(`<div style="display:flex;align-items:center;gap:12px">${chip(`${L.SUGGESTED}: Home`, { variant: 'soft', iconRight: ICON.CLOSE })}${fig('24 pt', { size: 'xs', tone: 'danger' })}</div>`),
    proposed: frame(`<div style="display:flex;align-items:center;gap:12px">${chip(`${L.SUGGESTED}: Home`, { variant: 'soft', iconRight: ICON.CLOSE, size: 's' })}${fig('32 pt + hit slop to 44', { size: 'xs', tone: 'positive' })}</div>`),
  },
  {
    id: 'UX-ACCOUNTS-TOTAL', area: 'Accounts', title: 'The total repeats the hero',
    why: 'Under "All" the Total row sums the base figures, which is the net worth two hundred points above it, to the cent.',
    now: frame(`${eyebrow(netEyebrow())}<div style="margin:4px 0 12px">${price(NET, { size: 'hero', bold: true })}</div>${accountRow(ACCOUNTS[0])}<div style="display:flex;justify-content:space-between;padding-top:12px">${eyebrow(L.TOTAL)}${price(NET, { size: 'lg', bold: true })}</div>`),
    proposed: frame(`${eyebrow(netEyebrow())}<div style="margin:4px 0 12px">${price(NET, { size: 'hero', bold: true })}</div>${accountRow(ACCOUNTS[0])}${accountRow(ACCOUNTS[1])}<div style="margin-top:8px">${text('the Total row only with a currency filter', { size: 'xxs', tone: 'muted' })}</div>`),
  },
  {
    id: 'UX-MODAL-TOKENS', area: 'Date sheet', title: 'A backdrop and a handle off the tokens',
    why: 'Modal.styles.js paints rgba(0, 0, 0, 0.35) where Confirm uses colors.overlay, and gives the handle a radius of 2 where dots are full.',
    now: `<div class="m" style="width:350px;padding:24px 0 0;background:rgba(0,0,0,0.35)"><div style="background:var(--color-background);border-radius:4px 4px 0 0;padding:12px 20px 16px;text-align:center"><span style="display:inline-block;width:32px;height:4px;border-radius:2px;background:var(--color-border)"></span><div style="margin-top:10px">${text('September 2026', { medium: true })}</div></div></div>`,
    proposed: `<div class="m" style="width:350px;padding:24px 0 0;background:var(--color-overlay)"><div style="background:var(--color-background);border-radius:4px 4px 0 0;padding:12px 20px 16px;text-align:center"><span style="display:inline-block;width:32px;height:4px;border-radius:9999px;background:var(--color-border)"></span><div style="margin-top:10px">${text('September 2026', { medium: true })}</div></div></div>`,
  },
  {
    id: 'UX-SEPARATORS', area: 'Settings', title: 'A hyphen among middle dots',
    why: 'The backup reminder subtitle is built with " - " while every other caption joins its parts with " · ".',
    now: frame(setting(L.REMINDER_BACKUP, { subtitle: `${L.SCHEDULED_PATTERN_WEEKLY} - Sun 08:00`, right: switchEl(true) })),
    proposed: frame(setting(L.REMINDER_BACKUP, { subtitle: `${L.SCHEDULED_PATTERN_WEEKLY} · Sun 08:00`, right: switchEl(true) })),
  },
];

const reviewBoards = () =>
  REVIEW.map(({ id, area, title, why, now, proposed }) => `<div class="kit-cell" data-review="${id}" style="grid-column: 1 / -1"><div class="kit-caption">${id} · ${esc(area)}</div><div class="kit-specimen" style="display:grid;grid-template-columns:1fr 1fr;gap:16px 24px"><div style="grid-column:1 / -1"><b style="font:600 15px/1.3 var(--font-sans)">${esc(title)}</b><p class="kit-note" style="margin:4px 0 0">${esc(why)}</p></div><div><div class="kit-caption" style="margin-bottom:8px">Now</div><div style="overflow:auto">${now}</div></div><div><div class="kit-caption" style="margin-bottom:8px">Proposed</div><div style="overflow:auto">${proposed}</div></div></div></div>`).join('');

const proposals = () => {
  counter = 0;
  const lanes = parseRoadmap();
  const list = (entries) =>
    entries.length
      ? entries
          .map((entry, index) => `${entry.group && (index === 0 || entries[index - 1].group !== entry.group) ? `<div class="kit-caption" style="margin:20px 0 4px">${esc(entry.group)}</div>` : ''}<article class="kit-proposal" data-task="${entry.id}"><span><span class="id">${entry.id}</span><br><span class="meta">${esc(entry.meta)}</span></span><span><span class="title">${esc(entry.title)}</span><br><span class="accept">${esc(entry.accept)}</span></span></article>`)
          .join('')
      : `<p class="kit-note">Nothing here.</p>`;
  const open = [...(lanes.Queue?.entries || []), ...(lanes['In progress']?.entries || []), ...(lanes['Needs creator']?.entries || [])];
  const discarded = lanes.Discarded?.rows || [];
  return page({
    file: 'proposals.html',
    title: 'Open work',
    intro: 'What is still pending, read from <code>ROADMAP.md</code>: the approved queue and what waits on the creator first, then the proposals nobody has approved yet. A row leaves when it ships; the changelog keeps the history.',
    body: [
      section('Design review', `<div class="kit-grid">${reviewBoards()}</div>`, `${REVIEW.length} findings from reading every screen against the design system, each drawn as it is and as proposed, each filed in ROADMAP under Proposed with what proves it done.`),
      section('Queue and needs creator', list(open), `${lanes.Queue?.entries.length || 0} in the queue · ${lanes['In progress']?.entries.length || 0} in progress · ${lanes['Needs creator']?.entries.length || 0} waiting on the creator.`),
      section('Proposed', list(lanes.Proposed?.entries || []), 'Ideas from the creator or the agent. Never worked on until approved into the queue.'),
      section('Discarded', `<table class="kit-table"><tr><th>decision</th><th>reason</th></tr>${discarded.map(([decision, reason]) => `<tr><td>${esc(decision)}</td><td>${esc(reason)}</td></tr>`).join('')}</table>`, "Don't relitigate."),
    ].join('\n'),
  });
};

export const renderPages = () => ({
  'tokens.css': tokensCss(),
  'index.html': system(),
  'mobile.html': mobile(),
  'proposals.html': proposals(),
});
