import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
export const read = (file) => readFileSync(join(ROOT, file), 'utf8');

export const evaluate = (file, scope = {}) => {
  const names = [...read(file).matchAll(/^export const (\w+)/gm)].map((m) => m[1]);
  const code = read(file)
    .replace(/^import .*$/gm, '')
    .replace(/^export const /gm, 'const ')
    .replace(/^export \{[^}]*\};?$/gm, '');
  const exports = {};
  new Function('exports', ...Object.keys(scope), `${code}\nObject.assign(exports, { ${names.join(', ')} });`)(
    exports,
    ...Object.values(scope),
  );
  return exports;
};

export const PKG = JSON.parse(read('package.json'));
export const { theme } = evaluate('src/theme/theme.js');
export const layout = evaluate('src/theme/layout.js', { theme });
export const { EN: L, DE, FR } = evaluate('src/i18n/dictionaries.js');
export const { ICON } = evaluate('src/modules/icon.js');
export const { GLYPHS } = evaluate('src/primitives/Icon/glyphs.js');
export const { C } = evaluate('src/modules/constants.js', { Platform: { OS: 'ios', Version: 0 }, PKG, __DEV__: false });

export const BASE = 'USD';
export const VERSION = PKG.version;
export const FONT_SANS = "'Euclid Circular A', 'Helvetica Neue', Arial, sans-serif";
export const FONT_MONO = "'Geist Mono', ui-monospace, Menlo, monospace";

export const kebab = (key) => key.replace(/([A-Z])/g, '-$1').toLowerCase();
export const esc = (value) => String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export const tokensCss = () => {
  const colours = (mode) =>
    Object.entries(theme.colors[mode])
      .map(([key, value]) => `  --color-${kebab(key)}: ${value};`)
      .join('\n');
  const spacing = Object.entries(theme.spacing)
    .map(([key, value]) => `  --space-${key}: ${value}px;`)
    .join('\n');
  const geometry = Object.entries(layout)
    .map(([key, value]) => `  --${kebab(key)}: ${value}px;`)
    .join('\n');
  return `/* Generated by yarn design from src/theme/theme.js and src/theme/layout.js. Do not edit. */
:root {
${colours('light')}
  --font-sans: ${FONT_SANS};
  --font-mono: ${FONT_MONO};
${spacing}
  --radius-sm: ${theme.borderRadius.sm}px;
  --radius-full: ${theme.borderRadius.full}px;
  --hairline: ${theme.hairline}px;
  --motion-quick: ${theme.animations.duration.quick}ms;
  --motion-standard: ${theme.animations.duration.standard}ms;
${geometry}
}
:root.dark {
${colours('dark')}
}
`;
};

export const TONE = { muted: 'muted', secondary: 'secondary', accent: 'accent', positive: 'positive', danger: 'danger', onAccent: 'on-accent', onAccentSoft: 'on-accent-soft', onInverse: 'on-inverse' };
export const ICON_SIZES = { xxs: 11, xs: 13, s: 15, m: 17, l: 20, xl: 24 };

export const icon = (name, { size = 'm', tone } = {}) => {
  const glyph = GLYPHS[name];
  if (!glyph) return '';
  const px = typeof size === 'number' ? size : ICON_SIZES[size];
  const colour = tone ? `color: var(--color-${kebab(tone)})` : '';
  return `<svg width="${px}" height="${px}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" style="flex-shrink:0;${colour}">${glyph.map((d) => `<path d="${d}"/>`).join('')}</svg>`;
};

export const text = (content, { size = 'm', tone, medium, bold, center, uppercase, style = '' } = {}) => {
  const classes = ['m-text', size !== 'm' ? size : '', TONE[tone] || '', medium ? 'medium' : '', bold ? 'bold' : '', center ? 'center' : '', uppercase ? 'uppercase' : ''].filter(Boolean).join(' ');
  return `<span class="${classes}"${style ? ` style="${style}"` : ''}>${esc(content)}</span>`;
};

export const fig = (content, { size = 'md', tone, bold, style = '' } = {}) =>
  `<span class="m-fig ${size}${bold ? ' bold' : ''}${TONE[tone] ? ` ${TONE[tone]}` : ''}"${style ? ` style="${style}"` : ''}>${content}</span>`;

export const decimals = (value, currency) => {
  const max = C.FIXED[currency] !== undefined ? C.FIXED[currency] : 2;
  if (max <= 2) return max;
  const [, rest = ''] = Math.abs(value).toFixed(max).split('.');
  return Math.max(2, rest.replace(/0+$/, '').length);
};
export const formatters = new Map();
export const format = (value, places) => {
  if (!formatters.has(places)) formatters.set(places, new Intl.NumberFormat('en-US', { minimumFractionDigits: places, maximumFractionDigits: places }));
  return formatters.get(places).format(Math.abs(value));
};

// PriceFriendly: sign, whole, muted cents, and the symbol only for a foreign currency.
export const price = (value, { currency = BASE, size = 'md', bold, tone, operator, symbol, masked, fixed } = {}) => {
  const resolvedTone = tone !== undefined ? tone : operator && value > 0 ? 'positive' : undefined;
  if (masked) return fig('••••', { size, bold, tone: resolvedTone });
  const formatted = format(value, fixed !== undefined ? fixed : decimals(value, currency));
  const dot = formatted.lastIndexOf('.');
  const whole = dot < 0 ? formatted : formatted.slice(0, dot);
  const cents = dot < 0 ? '' : formatted.slice(dot);
  const sign = value < 0 ? '−' : operator && value > 0 ? '+' : '';
  const mark = symbol && currency !== BASE ? `<span class="symbol">${esc(C.SYMBOL[currency] || currency)}</span>` : '';
  return `<span class="m-price">${fig(`${sign}${whole}${cents ? `<span class="cents">${cents}</span>` : ''}${mark ? ` ${mark}` : ''}`, { size, bold, tone: resolvedTone })}</span>`;
};

export const percent = (value, { places = 1, signed = true } = {}) => `${signed && value > 0 ? '+' : value < 0 ? '−' : ''}${Math.abs(value).toFixed(places)}%`;

export const delta = (value, { caption, plain, inverted, places = 1, size = 'xs' } = {}) => {
  const wanted = inverted ? value < 0 : value > 0;
  const figure = fig(percent(value, { places }), { size, tone: wanted ? 'positive' : undefined });
  return `<span class="m-delta">${plain ? figure : `<span class="chip${wanted ? ' wanted' : ''}">${figure}</span>`}${caption ? text(caption, { size: 'xxs', tone: 'muted' }) : ''}</span>`;
};

export const eyebrow = (content, { tone, style = '' } = {}) => `<span class="m-eyebrow${tone ? ` ${tone}` : ''}"${style ? ` style="${style}"` : ''}>${esc(content)}</span>`;
export const heading = (value, { eyebrow: label, actions = '' } = {}) => `<div class="m-heading"><b>${esc(value)}</b>${label ? eyebrow(label) : ''}${actions ? `<span class="actions">${actions}</span>` : ''}</div>`;
export const btn = (label, { variant = 'primary', size = 'm', disabled, grow, iconName } = {}) =>
  `<span class="m-btn${variant !== 'primary' ? ` ${kebab(variant)}` : ''}${size !== 'm' ? ` ${size}` : ''}${disabled ? ' disabled' : ''}${grow ? ' grow' : ''}${iconName && !label ? ' icon' : ''}">${iconName ? icon(iconName, { size: 'l' }) : ''}${label ? esc(label) : ''}</span>`;
export const chip = (label, { variant = 'muted', size = 'xs', iconName, iconRight, shape } = {}) =>
  `<span class="m-chip${variant !== 'muted' ? ` ${variant}` : ''}${size === 's' ? ' s' : ''}${shape === 'circle' ? ' circle' : ''}">${iconName ? icon(iconName, { size: 'xxs' }) : ''}${esc(label)}${iconRight ? icon(iconRight, { size: 'xxs' }) : ''}</span>`;
export const check = (on) => `<span class="m-check${on ? ' on' : ''}">${on ? icon(ICON.CHECK, { size: 'xxs' }) : ''}</span>`;
export const switchEl = (on) => `<span class="m-switch${on ? ' on' : ''}"></span>`;
export const seg = (options, value, { compact, auto } = {}) =>
  `<div class="m-seg${compact ? ' compact' : ''}${auto ? ' auto' : ''}">${options.map((option) => `<span${option === value ? ' class="on"' : ''}>${esc(option)}</span>`).join('')}</div>`;
export const iconButton = (name) => `<span class="m-iconbtn">${icon(name)}</span>`;
export const seal = (floating) => `<span class="m-seal${floating ? ' floating' : ''}">${icon(ICON.ADD, { size: 'l' })}</span>`;
export const logo = () => `<span class="m-logo">MÔNEY</span>`;
export const mark = (size = 44) => `<span class="m-mark" style="width:${size}px;height:${size}px;font-size:${Math.round(size * 0.42)}px">MÔ</span>`;

export const proposalRow = (title, where, value, { currency = 'THB', mark } = {}) => `<div style="display:flex;align-items:center;gap:8px;min-height:44px;border-top:var(--hairline) solid var(--color-border)"><span style="flex:1;display:flex;flex-direction:column">${text(title, { size: 's', medium: true })}${text(where, { size: 'xxs', tone: 'muted' })}</span>${mark ? chip(mark, { variant: 'outline' }) : ''}${price(value, { currency, operator: !!mark, tone: 'accent', symbol: true })}</div>`;
export const emptyState = (title, caption, action) => `<div class="m-empty"><span class="m-well">${icon(ICON.RECEIPT, { size: 'xl', tone: 'textMuted' })}</span><div style="height:16px"></div>${text(title, { size: 'l', bold: true })}<div style="height:8px"></div>${text(caption, { size: 's', tone: 'muted', center: true, style: 'max-width:250px' })}<div style="height:24px"></div>${btn(action, { variant: 'outlined' })}</div>`;
export const fieldRow = (label, value, { divider, chevron } = {}) =>
  `<div class="m-fieldrow${divider ? ' divider' : ''}"><span class="label">${esc(label)}</span><span class="value">${value}</span>${chevron ? icon(ICON.DOWN, { size: 's', tone: 'textMuted' }) : ''}</div>`;
export const input = (value, { placeholder = '...', right, figure } = {}) =>
  `<span class="m-input${right ? ' right' : ''}${figure ? ' figure' : ''}">${value ? esc(value) : `<span class="placeholder">${esc(placeholder)}</span>`}</span>`;
export const setting = (title, { subtitle, right = '', divider, tone } = {}) =>
  `<div class="m-setting${divider ? ' divider' : ''}"><span class="text">${text(title, { medium: true, tone })}${subtitle ? `<br>${text(subtitle, { size: 'xs', tone: 'muted' })}` : ''}</span><span class="right">${right}</span></div>`;
export const chevronRight = () => icon(ICON.RIGHT, { size: 's', tone: 'textMuted' });
export const rightValue = (value, { figure } = {}) => `${figure ? fig(esc(value), { size: 'sm', tone: 'muted' }) : text(value, { size: 's', tone: 'muted' })}${chevronRight()}`;

export const masthead = ({ section, back, sheet, actions = '', search, rule = true } = {}) => {
  const left = search
    ? `<span class="left" style="flex:1;height:34px;border:var(--hairline) solid var(--color-border);border-radius:var(--radius-sm);padding:0 12px;gap:8px">${icon(ICON.SEARCH, { size: 's', tone: 'textMuted' })}${input('', { placeholder: `${L.SEARCH}…` })}</span>`
    : back
      ? `<span class="left">${iconButton(ICON.BACK)}<span class="m-title">${esc(section)}</span></span>`
      : `<span class="left">${logo()}</span>`;
  const right = search
    ? iconButton(ICON.CLOSE)
    : `<span class="right">${!back && section ? eyebrow(section) : ''}${actions}${sheet ? iconButton(ICON.CLOSE) : ''}</span>`;
  return `<div class="m-masthead">${left}${right}</div>${rule && !sheet ? '<div class="m-rule"></div>' : ''}`;
};

export const TABS = [L.OVERVIEW, L.ACCOUNTS, null, L.ACTIVITY, L.SETTINGS];
export const footer = (active) =>
  `<div class="m-footer">${TABS.map((tab) => (tab === null ? seal() : `<span class="tab${tab === active ? ' on' : ''}">${text(tab, { size: 'xs', medium: tab === active, tone: tab === active ? undefined : 'muted' })}</span>`)).join('')}</div>`;
export const statusBar = () => `<div class="m-status"><span class="figure">9:41</span><span class="figure">●●●</span></div>`;

export const phone = (name, caption, body, { sheet, fold, tab } = {}) =>
  `<div class="kit-board" data-screen="${name}"><div class="kit-caption">${esc(caption)}</div><div class="m kit-phone${sheet ? ' sheet' : ''}${fold ? ' fold' : ''}">${statusBar()}${fold ? `<div style="max-width:480px;margin:0 auto">${body}</div>` : body}${tab ? footer(tab) : ''}</div></div>`;
export const content = (body, style = '') => `<div class="m-content"${style ? ` style="${style}"` : ''}>${body}</div>`;

export const linePoints = (series, { width, height, padding, min, max }) =>
  series.map((value, index) => [
    padding + (index * (width - padding * 2)) / (series.length - 1),
    padding + ((max - value) * (height - padding * 2)) / (max - min || 1),
  ]);
export const pathOf = (points) => points.map(([x, y], index) => `${index ? 'L' : 'M'}${x.toFixed(1)} ${y.toFixed(1)}`).join(' ');
export const compact = (value) => (Math.abs(value) >= 1000 ? `${(value / 1000).toFixed(value >= 10000 ? 0 : 1)}k` : `${Math.round(value)}`);

export const chart = ({ values, trend, labels, pointer }) => {
  const width = 350;
  const height = 112;
  const padding = 10;
  const all = [...values, ...trend];
  const min = Math.min(...all);
  const max = Math.max(...all);
  const points = linePoints(values, { width, height, padding, min, max });
  const trendPoints = linePoints(trend, { width, height, padding, min, max });
  const last = points[points.length - 1];
  const selected = pointer !== undefined ? points[pointer] : undefined;
  const grid = [max, (max + min) / 2, min];
  return `<div class="m-chart"><div style="position:absolute;left:0;top:${padding - 12}px;height:${height - padding * 2}px;display:flex;flex-direction:column;justify-content:space-between">${grid.map((value) => fig(compact(value), { size: 'xs', tone: 'muted' })).join('')}</div><svg viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">${grid.map((_, index) => `<line x1="0" x2="${width}" y1="${padding + (index * (height - padding * 2)) / 2}" y2="${padding + (index * (height - padding * 2)) / 2}" stroke="var(--color-border)" stroke-width="1"/>`).join('')}<path d="${pathOf(trendPoints)}" fill="none" stroke="var(--color-text-muted)" stroke-width="1.5" stroke-dasharray="3 4"/><path d="${pathOf(points)}" fill="none" stroke="var(--color-text)" stroke-width="1.5"/>${selected ? `<line x1="${selected[0]}" x2="${selected[0]}" y1="${padding}" y2="${height - padding}" stroke="var(--color-text-muted)" stroke-width="1" stroke-dasharray="2 3"/><circle cx="${selected[0]}" cy="${selected[1]}" r="4" fill="var(--color-background)" stroke="var(--color-text)" stroke-width="1.5"/>` : ''}<circle cx="${last[0]}" cy="${last[1]}" r="4" fill="var(--color-accent)"/></svg><div class="m-axis">${labels.map((label) => eyebrow(label)).join('')}</div><div class="m-chart-legend"><span><i style="display:inline-block;width:14px;height:0;border-top:1.5px solid var(--color-text)"></i>${text(L.BALANCE, { size: 'xxs', tone: 'muted' })}</span><span><i style="display:inline-block;width:14px;height:0;border-top:1.5px dashed var(--color-text-muted)"></i>${text(L.TREND, { size: 'xxs', tone: 'muted' })}</span></div></div>`;
};

export const flowChart = ({ incomes, expenses, labels, selected, figureLabels }) => {
  const width = 350;
  const height = 132;
  const slot = width / 6;
  const baseline = height / 2;
  const peak = Math.max(...incomes, ...expenses);
  const scale = (baseline - 12) / peak;
  const median = (list) => [...list].sort((a, b) => a - b)[Math.floor(list.length / 2)];
  const bars = incomes.map((income, index) => {
    const x = index * slot + slot * 0.25;
    const w = slot * 0.5;
    const up = income * scale;
    const down = expenses[index] * scale;
    return `<rect x="${x.toFixed(1)}" y="${(baseline - up).toFixed(1)}" width="${w.toFixed(1)}" height="${up.toFixed(1)}" fill="var(--color-accent)"/><rect x="${x.toFixed(1)}" y="${baseline}" width="${w.toFixed(1)}" height="${down.toFixed(1)}" fill="var(--color-text)"/>`;
  });
  const incomeY = baseline - median(incomes) * scale;
  const expenseY = baseline + median(expenses) * scale;
  return `<div class="m-chart"><svg viewBox="0 0 ${width} ${height}" width="${width}" height="${height}"><line x1="0" x2="${width}" y1="${baseline}" y2="${baseline}" stroke="var(--color-border)"/><line x1="0" x2="${width}" y1="${incomeY.toFixed(1)}" y2="${incomeY.toFixed(1)}" stroke="var(--color-accent)" stroke-dasharray="2 3"/><line x1="0" x2="${width}" y1="${expenseY.toFixed(1)}" y2="${expenseY.toFixed(1)}" stroke="var(--color-text-muted)" stroke-dasharray="2 3"/>${bars.join('')}${selected !== undefined ? `<rect x="${(selected * slot).toFixed(1)}" y="0" width="${slot.toFixed(1)}" height="${height}" fill="var(--color-text)" opacity="0.06"/>` : ''}</svg><div class="m-axis" style="display:grid;grid-template-columns:repeat(6,1fr);text-align:center">${labels.map((label, index) => (figureLabels ? fig(label, { size: 'xs', tone: 'muted' }) : eyebrow(label, { tone: index === selected ? 'ink' : undefined }))).join('')}</div><div class="m-chart-legend"><span><i class="m-dot" style="background:var(--color-accent)"></i>${text(L.FLOW_IN, { size: 'xxs', tone: 'muted' })}</span><span><i class="m-dot" style="background:var(--color-text)"></i>${text(L.FLOW_OUT, { size: 'xxs', tone: 'muted' })}</span><span><i style="display:inline-block;width:14px;border-top:1px dashed var(--color-text-muted)"></i>${text(L.TYPICAL, { size: 'xxs', tone: 'muted' })}</span></div></div>`;
};

export const txRow = ({ time, title, category, value, currency, base, income }) =>
  `<div class="m-row"><span class="time">${fig(time, { size: 'xs', tone: 'muted' })}</span><span class="text">${text(title, { medium: true })}${text(category, { size: 'xxs', tone: 'muted' })}</span><span class="amount">${price(income ? value : -value, { currency, size: 'md', bold: true, operator: income, symbol: true })}${base !== undefined ? price(income ? base : -base, { size: 'xs', tone: 'muted' }) : ''}</span></div>`;
export const dayHead = (label, net) => `<div class="m-dayhead">${eyebrow(label, { tone: 'ink' })}${net ? price(net, { size: 'xs', operator: true, tone: net > 0 ? 'positive' : 'muted' }) : ''}</div>`;
export const accountRow = ({ title, currency, balance, base, change }) =>
  `<div class="m-row" style="padding:10px 0"><span class="text">${balance < 0 ? `<span style="display:flex;align-items:center;gap:8px">${text(title, { medium: true })}${chip(L.OWED, { variant: 'outline' })}</span>` : text(title, { medium: true })}${text(currency, { size: 'xxs', tone: 'muted' })}</span><span class="amount">${price(balance, { currency, size: 'lg', bold: true, symbol: true })}${base !== undefined ? price(base, { size: 'xs', tone: 'muted' }) : change !== undefined ? delta(change, { plain: true }) : fig('—', { size: 'xs', tone: 'muted' })}</span></div>`;

export const monthRow = (label, body, tail) => `<div style="display:flex;align-items:baseline;gap:8px;padding:7px 0;border-bottom:var(--hairline) solid var(--color-border)"><span style="width:96px">${text(label, { size: 's', tone: 'muted' })}</span><span style="flex:1">${body}</span>${tail}</div>`;

export const monthSummary = ({ spent, baseline, pace, day, swing, swingCategory, scheduled, pending, closed, closedHint, lines = '' }) => {
  const scale = Math.max(spent, baseline);
  const fill = Math.min(spent, baseline) / scale;
  const line = (label, value, hint, { action, operator, tone } = {}) =>
    monthRow(label, price(value, { size: 'md', operator, tone }), action ? `<span style="display:flex;align-items:center;gap:4px">${eyebrow(action, { tone: 'ink' })}${icon(ICON.RIGHT, { size: 's', tone: 'textMuted' })}</span>` : text(hint, { size: 'xs', tone: 'muted' }));
  return `<div style="margin-top:4px"><div style="padding:8px 0 12px;border-bottom:var(--hairline) solid var(--color-border)"><div style="display:flex;align-items:baseline;gap:8px"><span style="width:96px">${text(L.SPENT_SO_FAR, { size: 's', tone: 'muted' })}</span><span style="flex:1">${price(spent, { size: 'md' })}</span>${text(pace, { size: 'xs', tone: 'muted' })}</div><div class="m-bar" style="margin:9px 0 6px"><div class="fill" style="width:${(fill * 100).toFixed(1)}%"></div><span class="tick" style="left:${((baseline / scale) * 100).toFixed(1)}%"></span></div><div style="display:flex;align-items:baseline;gap:4px">${text(`${L.USUAL_BY(day)} · `, { size: 'xxs', tone: 'muted' })}${price(baseline, { size: 'xs', tone: 'muted' })}</div></div>${closed !== undefined ? line(L.LAST_MONTH, closed, closedHint) : ''}${line(L.SWING, swing, `${swingCategory}, ${swing < 0 ? L.BELOW_USUAL : L.ABOVE_USUAL}`)}${lines}${line(L.SCHEDULED_AHEAD, scheduled, undefined, { action: L.SEE_ALL_COUNT(pending), operator: true })}</div>`;
};

export const NAV = [
  ['index.html', 'System'],
  ['mobile.html', 'Mobile'],
  ['proposals.html', 'Proposals'],
];
export const FACTS = `<div class="kit-facts"><span>sources src/theme/theme.js · src/theme/layout.js · src/i18n · src/modules/icon.js · ROADMAP.md</span><span>type Euclid Circular A · Geist Mono</span><span>icons Lucide · 1.5 stroke</span><span>regenerate yarn design</span></div>`;

export const page = ({ file, title, intro, body }) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Môney design · ${esc(title)}</title>
<link rel="icon" href="favicon.png">
<link rel="stylesheet" href="tokens.css">
<link rel="stylesheet" href="kit.css">
<script src="kit.js" defer></script>
</head>
<body class="kit">
<header class="kit-header"><a class="kit-brand" href="index.html">MÔNEY</a><nav class="kit-nav" aria-label="Design kit">${NAV.map(([href, label]) => `<a href="${href}"${href === file ? ' aria-current="page"' : ''}>${label}</a>`).join('')}</nav><span class="kit-version">v${VERSION} · iOS and Android</span><div class="kit-theme" role="group" aria-label="Theme"><button type="button" data-kit-theme="light">Light</button><button type="button" data-kit-theme="dark">Dark</button></div></header>
<main class="kit-main">
<section class="kit-intro"><h1>${esc(title)}</h1><p>${intro}</p>${FACTS}</section>
${body}
</main>
</body>
</html>
`;

let counter = 0;
export const restart = () => {
  counter = 0;
};
export const section = (title, body, note) => `<section class="kit-section"><h2>${esc(title)}<span>${String(++counter).padStart(2, '0')}</span></h2>${note ? `<p>${note}</p>` : ''}${body}</section>`;
export const cell = (caption, body, { component, wide, sheet, stack, row } = {}) =>
  `<div class="kit-cell"${component ? ` data-component="${component}"` : ''}${wide ? ' style="grid-column: span 2"' : ''}><div class="kit-caption">${esc(caption)}</div><div class="m kit-specimen${sheet ? ' sheet' : ''}${stack ? ' stack' : ''}${row ? ' row' : ''}">${body}</div></div>`;
export const grid = (cells, wide) => `<div class="kit-grid${wide ? ' wide' : ''}">${cells.join('')}</div>`;
export const ACCOUNTS = [
  { title: 'Chase', currency: 'USD', balance: 12480.55, change: 3.2 },
  { title: 'Wallet', currency: 'THB', balance: 34596, base: 1052.61 },
  { title: 'N26', currency: 'EUR', balance: 3210, base: 3720.44 },
  { title: 'Cold wallet', currency: 'BTC', balance: 0.52, base: 42197.14 },
];
export const NET = 61648.74;
export const CARD = { title: 'Visa', currency: 'USD', balance: -1284.3, base: -1284.3 };
export const netEyebrow = () => `${L.NET_WORTH} · ${ACCOUNTS.length} ${L.ACCOUNTS_CAPTION(ACCOUNTS.length)} · ${BASE}`;

const BUDGET_ROWS = [
  { name: 'Personal', limit: 300, spent: 226, color: 'accent' },
  { name: 'Transit', limit: 100, spent: 121, color: 'text' },
  { name: 'Food & Drinks', limit: 120, spent: 105, color: 'textSecondary' },
  { name: 'Leisure', spent: 61, pct: 11, color: 'textMuted' },
];
const budgetState = ({ limit, spent }) => (!limit ? 'none' : spent > limit ? 'over' : spent / limit >= 0.8 ? 'near' : 'within');

export const budgetCategories = () =>
  BUDGET_ROWS.map((row) => {
    const state = budgetState(row);
    const share = row.pct || Math.round((row.spent / 552.78) * 100);
    const fillColor = { over: 'danger', near: 'accent', within: 'text', none: kebab(row.color) }[state];
    const width = state === 'none' ? share : Math.min(100, Math.round((row.spent / row.limit) * 100));
    const note = state === 'none' ? `${share}%` : state === 'over' ? `+${row.spent - row.limit}` : L.BUDGET_OF(`${row.limit}`);

    return `<div class="m-category"><i class="m-dot" style="width:9px;height:9px;background:var(--color-${kebab(row.color)})"></i><span style="flex:1">${text(row.name, { size: 's' })}</span><span class="track" style="max-width:96px"><i class="fill" style="display:block;width:${width}%;background:var(--color-${fillColor})"></i></span>${fig(note, { size: 'xs', tone: state === 'over' ? 'danger' : 'muted', style: 'min-width:34px;text-align:right' })}${price(row.spent, { fixed: 0, bold: true, tone: state === 'over' ? 'danger' : undefined })}</div>`;
  }).join('');

export const budgetBlock = () =>
  `<div style="margin-top:16px"><div class="m-bar" style="margin-bottom:8px"><div class="fill" style="width:65.5%"></div></div>${fieldRow(L.BUDGET, fig('300', { size: 'md' }))}<div style="display:flex;align-items:baseline;gap:8px;padding-bottom:8px">${price(45, { size: 'xs', tone: 'muted' })}${text(L.BUDGET_CARRIED, { size: 'xs', tone: 'muted' })}</div>${monthRow(L.BUDGET_LEFT, price(119, { size: 'md' }), text(L.BUDGET_OF('345'), { size: 'xs', tone: 'muted' }))}</div>`;
